### ISSUE TITLE
Add a parser result object

### ISSUE THREAD

**Issue by tenderlove** [ruby/prism#1142]
Right now `yp_parse` [only returns an AST node](https://github.com/ruby/yarp/blob/a8904e013e767c6793d9acaa32348471aa39dd5e/src/yarp.c#L12882-L12883).  This is kind of cumbersome because as the compiler recurses the AST, we must pass a node and a parser object in order to get data such as newline information.

I think newline information shouldn't be stored on the parser, but rather a parse result object.  The result object should contain information that's contextually important to the document we parsed, but isn't associated wit _a parser_ (newline information being a prime example).

**Comment by eregon** [comment]
This is already the case in the Ruby API: https://github.com/ruby/yarp/blob/a8904e013e767c6793d9acaa32348471aa39dd5e/lib/yarp.rb#L147
We should do the same for the Java API (I can do that),
and for the C API too, as you say.

**Comment by eregon** [comment]
Related:
https://github.com/ruby/yarp/pull/1112#discussion_r1249513857
https://github.com/ruby/yarp/pull/1112#discussion_r1249517829

**Comment by kddnewton** [comment]
We have this now in the prism compiler in CRuby.
