### ISSUE TITLE
Serialization of piped Ruby source code

### ISSUE THREAD

**Issue by enebo** [ruby/prism#1247]
Almost all Ruby source is processed as an in-memory block of bytes.  I just remembered ```some_piped_output | ruby -``` is not.  In this case the parsing will be to make ```$stdin``` into an ```IO``` and using ```IO#gets``` to process each line.  How do we support this?  MRI obviously also needs this and we perhaps just need a second entry point where instead of passing in a source blob we pass in an fd (and then leverage the same code MRI does in the lexer for this).

**Comment by eregon** [comment]
Are you sure it's incrementally reading from $stdin?
AFAIK Ruby reads all of `$stdin` and then only parses:

When using a TTY Ruby or the shell waits for the whole input:
```
$ ruby
p 1
sleep 1
p 2
Ctrl+D
1 # only printed after Ctrl+D, i.e. end of input
2
```

And on
```
$ sh -c "echo 'p 1'; sleep 1; echo 'p 2'" | ruby
1
2
```
nothing appears before one second, so at least the `p 1` is not executed and probably not parsed before end-of-input.

**Comment by enebo** [comment]
@eregon I am befuddled.

**Comment by enebo** [comment]
Ah so this is a problem after all:

```text
sh -c "echo 'DATA.each_line do |line| puts line; end'; echo '__END__'; echo '1'; sleep 5; echo '2'"; sleep 5; echo '3' | ruby -
```

In this case when we hit __END__ the parsing is finished so the code executes but stdin is still open and can be piping the data after __END__.

**Comment by kddnewton** [comment]
Oh man, I am scared about this. This violates one of my fundamental assumptions that it was okay to replace the line-fetching code with mmap. I really did not realize this was a path. There is a ton of bookkeeping that goes into making this happen in CRuby right now, particularly around heredocs where you have to jump back and forth between multiple lines. I'll take a look to see if there's an easy way, but I'm nervous.

**Comment by kddnewton** [comment]
Actually @enebo is the _only_ case where this is an issue when we hit `__END__`? In that case we could specially handle it with just that condition.

**Comment by enebo** [comment]
@kddnewton HAHA.  I hope so.  It took me like an hour to remember this case.  I think the fundamentals though would be that no AST is produced until ^D or ```__END__``` so any streaming behavior would be after that point (who cares about seeing inline syntax warns/errors while it actively streams).  All I can brainstorm is there could be some super esoteric command-line option?

**Comment by kddnewton** [comment]
Okay, in this case I'm happy to supply an API where you provide an `fd` and you get back a pointer to the AST.

In the case that you're reading after `__END__`, in that case the consumer could actually continue to read from the same `fd` because at that point we would have consumed the whole AST, the `fd` will be pointing to the content of `DATA`.

So... maybe this just solves itself?

**Comment by enebo** [comment]
@kddnewton Maybe?  I need to look at our IO.   On non-windows I think we are now dealing with native descriptors but I need to verify how this all works is native IO is disabled (e.g. pure Java mode).  On windows, descriptors are FILEHANDLE and I think we do not have that.

Worst case I think we would implement an interface which was a pointer to a function.  This is similar to how MRI does this with the ```->gets``` call.  It would allow any external system to implement IO however it wanted so it might be a more portable way of supporting this.

**Comment by kddnewton** [comment]
@enebo I like that solution. What do you think of something that returns a pointer to a `yp_string_t` or `NULL`? (`NULL` would indicate end-of-stream, otherwise we could handle adding the source together).

**Comment by enebo** [comment]
@kddnewton I am not so sure on yp_string_t.  It is possible but we need to make struct from another language so I think it raises the bar.   I guess we have to supply a length and some data and that is what this struct is beyond type.  If we wanted to eliminate struct altogether it could be another "{4byte length}data"?  Ownership then would be given to yarp to clean up.

This is just me trying to not use structs :smiley:

**Comment by enebo** [comment]
Also a related question what is the max line length of Ruby?  Is it really size_t?

**Comment by kddnewton** [comment]
That's fine, we can make that happen.

The issue I'm running into now is how to be sure the AST is done. With source that has syntax errors, how would we know to stop waiting on input?

**Comment by kddnewton** [comment]
> Also a related question what is the max line length of Ruby? Is it really size_t?

I think it might be `int`. We should probably match that.

**Comment by enebo** [comment]
```c
static VALUE
lex_generic_gets(struct parser_params *p, VALUE input)
{
    return (*p->lex.gets_.call)(input, p->line_count);
}
```

It seems to be same size as a Ruby String.

**Comment by enebo** [comment]
ah but beg/end col are int and I pretty much see int littered around.  I wonder what happens if we supply a long Ruby String back in MRI.  I bet some pretty interesting things happen.

**Comment by eregon** [comment]
> Ah so this is a problem after all:
> 
> ```
> sh -c "echo 'DATA.each_line do |line| puts line; end'; echo '__END__'; echo '1'; sleep 5; echo '2'"; sleep 5; echo '3' | ruby -
> ```
> 
> In this case when we hit **END** the parsing is finished so the code executes but stdin is still open and can be piping the data after **END**.

Scary.

But also this gives me on CRuby 3.1:
```
$ sh -c "echo 'DATA.each_line do |line| puts line; end'; echo '__END__'; echo '1'; sleep 5; echo '2'"; sleep 5; echo '3' | ruby -
DATA.each_line do |line| puts line; end
__END__
1
2
```
It doesn't print the `3` it seems, is that expected?

And the same behavior happens on TruffleRuby, but TruffleRuby doesn't handle STDIN specially, it reads all of it immediately.
So maybe the incremental parsing isn't really observable after all?

**Comment by enebo** [comment]
@eregon yeah I saw the same behavior and JRuby also does it.  Feels like a missing flush to me but who knows?  That behavior no doubt has been there for decades so it does underscore a point about who does this; but streaming or no people definitely use DATA in the real world.  We added it on request at some point (memories fade and come into focus).

Both MRI and JRuby will emit warns/errors the moment the line is read but beyond noticing it in a terminal window I doubt anyone relies on it.   Obviously, ```__END__``` + ```DATA``` is lifted from PERL.  Does anyone use that with piped input?  You just know there is someone :smile:

**Comment by headius** [comment]
Additional visible effect of this: early errors should terminate parse of a large streaming source. For example:

```
$ ruby -e '10_000_000.times { puts "1" }' | time ruby 
ruby  2.41s user 0.15s system 97% cpu 2.624 total
$ ruby -e 'puts "end"; 10_000_000.times { puts "1" }' | time ruby
-:1: syntax error, unexpected `end'
-: compile error (SyntaxError)
ruby  0.09s user 0.02s system 26% cpu 0.425 total
```

> With source that has syntax errors, how would we know to stop waiting on input?

If you don't terminate e.g. a `class` it does wait forever:

```
$ ruby -e 'puts "class"; sleep 5' | time ruby
-:1: syntax error, unexpected end-of-input
class
-: compile error (SyntaxError)
ruby  0.09s user 0.02s system 1% cpu 5.157 total
```

**Comment by enebo** [comment]
@headius This is a behavioral difference but I don't think one we should care about.    For the wait forever part we probably still wait forever since we are trying to read the complete source.  In old parser this is happening in lexing and in prism it is before the call to prism.

My rationale for the behavioral early error change is that this is very unlikely to be a real world problem.  If you cannot execute Ruby until the full source exists then the only value here would be to get a syntaxerror early without reading more from the pipe.  I just find this to be something no one would intentionally depend on.

The other side of this is prism is designed around providing the whole source as part of the call.  This is not a small ask to address this.

**Comment by eregon** [comment]
I looked at the example of https://github.com/ruby/prism/issues/1247#issuecomment-1677767048 again.
I tweaked it to add some debug print:
```
$ sh -c "echo 'p :START; DATA.each_line do |line| puts line; end'; echo '__END__'; echo '1'; sleep 5; echo '2'"; sleep 5; echo '3' | ruby -
p :START; DATA.each_line do |line| puts line; end
__END__
1
2
```
(in ZSH and in bash)
It never prints `:START`.
So my guess is this doesn't execute any Ruby code.

It seems Ruby acts like `cat` in that case for some reason.
And in fact the behavior seems almost the same with `cat` (also timing-wise):
```
$ sh -c "echo 'p :START; DATA.each_line do |line| puts line; end'; echo '__END__'; echo '1'; sleep 5; echo '2'"; sleep 5; echo '3' | cat   
p :START; DATA.each_line do |line| puts line; end
__END__
1
2
3
```

**Comment by eregon** [comment]
OK, this variant behaves in a more expected way:
```
$ sh -c "echo 'p :START; DATA.each_line { |line| p line }'; echo '__END__'; echo '1'; sleep 5; echo '2'; sleep 5; echo '3'" | ruby -
:START
"1\n"
"2\n"
"3\n"
```
And there it's clear it executes Ruby code.

I think that never worked on TruffleRuby, because it uses:
https://github.com/oracle/truffleruby/blob/a6aa1d83d4039722c795c46ab4f1525938e2e8bb/src/main/ruby/truffleruby/core/truffle/internal.rb#L38-L52
```ruby
file = File.open(path)
file.seek(offset)
```
and TruffleRuby reads the entire STDIN before doing anything.
Also one cannot lseek() on STDIN.

I suppose this could be solved by reading STDIN line by line (before calling to Prism), stop on `__END__` (and pass only that to Prism, not more), and set `DATA = STDIN` before executing.

**Comment by enebo** [comment]
@eregon In old parser main file is effectively made into a Ruby IO and the lexing will `gets` and parse.  When it finishes parsing and there is DATA it will just continue using the IO for DATA.

**Comment by eregon** [comment]
@enebo From what I understand of this, at least for this DATA case it should be possible to implement this completely outside of Prism, right? (see last paragraph in my previous comment)
If so, I think we should close this issue.

**Comment by enebo** [comment]
@eregon I think @kddnewton is looking into this so let's hold off and see but yeah we can implement something which reads stdin and finds `__END__` and then pass just the source off to Prism.  The main challenge is there are technically naturally occurring `__END__` that are not the actual end.  So we need a baby parser if we want a fool-proof way.

**Comment by eregon** [comment]
> The main challenge is there are technically naturally occurring `__END__` that are not the actual end. So we need a baby parser if we want a fool-proof way.

Ah true, I overlooked that.
Maybe we'd need a way to call the Prism lexer or so with partial input to find `__END__` properly.

For TruffleRuby I think it's fine it keeps reading the entire stdin at once as it always did, real-world code doesn't seem to depend on this much.
