### ISSUE TITLE
CRuby compilation

### ISSUE THREAD

**Issue by kddnewton** [ruby/prism#1335]
This is meant to serve as a meta-issue tracking the status of compiling the various YARP nodes in CRuby. Most of the work will be done in the CRuby codebase itself, but I'd like to track it here because things will inevitably arise that need changes here anyway. (Presumably we will need more entries in the constant table, there will probably be additional fields necessary, etc.)

I've attempted to group the nodes by relative functionality in order to give us a loose roadmap. Some/a lot of these are already complete, but I'm including all of them for transparency. Also, I don't want to mark them as "complete" until we get them fully merged into CRuby.

Below are all of the groups and nodes, along with checkboxes to track their status. Ideally, once we get PRs merged, we should mark them down here so that other contributors can see what goes in to implementing these.

## Literals

* [x] `FalseNode` - https://github.com/ruby/ruby/pull/8311
* [x] `FloatNode` - https://github.com/ruby/ruby/pull/8311
* [x] `ImaginaryNode` - https://github.com/ruby/ruby/pull/8311
* [x] `IntegerNode` - https://github.com/ruby/ruby/pull/8404
* [x] `NilNode` - https://github.com/ruby/ruby/pull/8311
* [x] `RationalNode` - https://github.com/ruby/ruby/pull/8404
* [x] `SelfNode` - https://github.com/ruby/ruby/pull/8311
* [x] `SourceEncodingNode` - https://github.com/ruby/ruby/pull/8328
* [x] `SourceFileNode` - https://github.com/ruby/ruby/pull/8328
* [x] `SourceLineNode` - https://github.com/ruby/ruby/pull/8328
* [x] `TrueNode` - https://github.com/ruby/ruby/pull/8311

## Reads

* [x] `BackReferenceReadNode` https://github.com/ruby/ruby/pull/8344
* [x] `ClassVariableReadNode` - https://github.com/ruby/ruby/pull/8311
* [x] `ConstantPathNode` - https://github.com/ruby/ruby/pull/8311
* [x] `ConstantReadNode` - https://github.com/ruby/ruby/pull/8311
* [x] `DefinedNode` - https://github.com/ruby/ruby/pull/8322
* [x] `GlobalVariableReadNode` - https://github.com/ruby/ruby/pull/8311
* [x] `InstanceVariableReadNode` - https://github.com/ruby/ruby/pull/8311
* [x] `LocalVariableReadNode` - https://github.com/ruby/ruby/pull/8322
* [x] `NumberedReferenceReadNode` https://github.com/ruby/ruby/pull/8344

## Writes

* [x] `ClassVariableAndWriteNode` - https://github.com/ruby/ruby/pull/8352
* [x] `ClassVariableOperatorWriteNode` - https://github.com/ruby/ruby/pull/8352
* [x] `ClassVariableOrWriteNode` - https://github.com/ruby/ruby/pull/8352
* [x] `ClassVariableWriteNode` - https://github.com/ruby/ruby/pull/8311
* [x] `ConstantAndWriteNode` - https://github.com/ruby/ruby/pull/8355
* [x] `ConstantOperatorWriteNode` - https://github.com/ruby/ruby/pull/8355
* [x] `ConstantOrWriteNode` - https://github.com/ruby/ruby/pull/8355
* [x] `ConstantWriteNode` - https://github.com/ruby/ruby/pull/8311
* [x] #1643 - https://github.com/ruby/ruby/pull/8774
* [x] #1644 - https://github.com/ruby/ruby/pull/8774
* [x] #1645 - https://github.com/ruby/ruby/pull/8774
* [x] `ConstantPathWriteNode` - https://github.com/ruby/ruby/pull/8311
* [x] `GlobalVariableAndWriteNode` - https://github.com/ruby/ruby/pull/8352
* [x] `GlobalVariableOperatorWriteNode` - https://github.com/ruby/ruby/pull/8352
* [x] `GlobalVariableOrWriteNode` - https://github.com/ruby/ruby/pull/8352
* [x] `GlobalVariableWriteNode` - https://github.com/ruby/ruby/pull/8311
* [x] #1780 - https://github.com/ruby/ruby/pull/9043
* [x] #1781 - https://github.com/ruby/ruby/pull/9043
* [x] #1782 - https://github.com/ruby/ruby/pull/9043
* [x] `InstanceVariableAndWriteNode` - https://github.com/ruby/ruby/pull/8352
* [x] `InstanceVariableOperatorWriteNode` - https://github.com/ruby/ruby/pull/8352
* [x] `InstanceVariableOrWriteNode` - https://github.com/ruby/ruby/pull/8352
* [x] `InstanceVariableWriteNode` - https://github.com/ruby/ruby/pull/8311
* [x] `LocalVariableAndWriteNode` - https://github.com/ruby/ruby/pull/8352
* [x] `LocalVariableOperatorWriteNode` - https://github.com/ruby/ruby/pull/8352
* [x] `LocalVariableOrWriteNode` - https://github.com/ruby/ruby/pull/8352
* [x] `LocalVariableWriteNode` - https://github.com/ruby/ruby/pull/8322
* [x] `MatchWriteNode` - https://github.com/ruby/ruby/pull/8496

## Multi-writes

* [x] `ClassVariableTargetNode` - https://github.com/ruby/ruby/pull/8469
* [x] `ConstantTargetNode` - https://github.com/ruby/ruby/pull/8470
* [x] `ConstantPathTargetNode` - https://github.com/ruby/ruby/pull/8488
* [x] `GlobalVariableTargetNode` - https://github.com/ruby/ruby/pull/8475
* [x] `InstanceVariableTargetNode` - https://github.com/ruby/ruby/pull/8471
* [x] `LocalVariableTargetNode` - https://github.com/ruby/ruby/pull/8471
* [x] #1646 - https://github.com/ruby/ruby/pull/8822
* [x] `MultiWriteNode` - https://github.com/ruby/ruby/pull/8322

## String-likes

* [x] `EmbeddedStatementsNode` - https://github.com/ruby/ruby/pull/8322
* [x] `EmbeddedVariableNode` - https://github.com/ruby/ruby/pull/8311
* [x] `InterpolatedMatchLastLineNode` - https://github.com/ruby/ruby/pull/8532
* [x] `InterpolatedRegularExpressionNode` - https://github.com/ruby/ruby/pull/8396
* [x] `InterpolatedStringNode` - https://github.com/ruby/ruby/pull/8311
* [x] `InterpolatedSymbolNode` - https://github.com/ruby/ruby/pull/8311
* [x] `InterpolatedXStringNode` - https://github.com/ruby/ruby/pull/8395
* [x] `MatchLastLineNode`
* [x] `RegularExpressionNode` - https://github.com/ruby/ruby/pull/8396
* [x] `StringConcatNode` - https://github.com/ruby/ruby/pull/8311
* [x] `StringNode`
* [x] `SymbolNode` - https://github.com/ruby/ruby/pull/8311
* [x] `XStringNode` - https://github.com/ruby/ruby/pull/8311

## Structures

* [x] `ArrayNode` - https://github.com/ruby/ruby/pull/8322
* [x] `AssocNode` - https://github.com/ruby/ruby/pull/8311
* [x] `AssocSplatNode` - https://github.com/ruby/ruby/pull/8322
* [x] `HashNode` - https://github.com/ruby/ruby/pull/8322
* [x] `ImplicitNode` - https://github.com/ruby/ruby/pull/8533
* [x] `RangeNode` - https://github.com/ruby/ruby/pull/8322
* [x] `SplatNode` - https://github.com/ruby/ruby/pull/8322

## Jumps

* [x] `AndNode` - https://github.com/ruby/ruby/pull/8311
* [x] #1647 - https://github.com/ruby/ruby/pull/8753
* [x] `ElseNode` - https://github.com/ruby/ruby/pull/8577
* [x] `FlipFlopNode` - https://github.com/ruby/ruby/pull/8322
* [x] #1648
* [x] `IfNode` - https://github.com/ruby/ruby/pull/8322
* [x] `OrNode` - https://github.com/ruby/ruby/pull/8311
* [x] `UnlessNode` - https://github.com/ruby/ruby/pull/8322
* [x] `UntilNode` - https://github.com/ruby/ruby/pull/8325
* [x] #1649 - https://github.com/ruby/ruby/pull/8753
* [x] `WhileNode` - https://github.com/ruby/ruby/pull/8322

## Throws

* [x] `BeginNode` - https://github.com/ruby/ruby/pull/8311
* [x] `BreakNode` - https://github.com/ruby/ruby/pull/8334
* [x] #1650
* [x] `NextNode` - https://github.com/ruby/ruby/pull/8334
* [x] `RedoNode` - https://github.com/ruby/ruby/pull/8334
* [x] #1651
* [x] #1652
* [x] #1653
* [x] `ReturnNode` - https://github.com/ruby/ruby/pull/8311

## Scopes/statements

* [x] #1654 - https://github.com/ruby/ruby/pull/8725
* [x] `ClassNode` - https://github.com/ruby/ruby/pull/8322
* [x] `DefNode` - https://github.com/ruby/ruby/pull/8322
* [x] `LambdaNode` - https://github.com/ruby/ruby/pull/8322
* [x] `ModuleNode` - https://github.com/ruby/ruby/pull/8322
* [x] `ParenthesesNode` - https://github.com/ruby/ruby/pull/8311
* [x] #1655 - https://github.com/ruby/ruby/pull/8752
* [x] `PreExecutionNode` - https://github.com/ruby/ruby/pull/8743
* [x] `ProgramNode` - https://github.com/ruby/ruby/pull/8311
* [x] `SingletonClassNode` - https://github.com/ruby/ruby/pull/8322
* [x] `StatementsNode` - https://github.com/ruby/ruby/pull/8311
* [x] `YieldNode` - https://github.com/ruby/ruby/pull/8322

## Calls/arguments

* [x] `ArgumentsNode` - https://github.com/ruby/ruby/pull/8311
* [x] `BlockArgumentNode` - https://github.com/ruby/ruby/pull/8499
* [x] #1656 - https://github.com/ruby/ruby/pull/8725
* [x] `CallNode` - https://github.com/ruby/ruby/pull/8322
* [x] #1657 - https://github.com/ruby/ruby/pull/8762
* [x] #1658 - https://github.com/ruby/ruby/pull/8762
* [x] #1659 - https://github.com/ruby/ruby/pull/8762
* [x] #1660 - https://github.com/ruby/ruby/pull/8873
* [x] #1661 - https://github.com/ruby/ruby/pull/8801
* [x] `KeywordHashNode` - https://github.com/ruby/ruby/pull/8311
* [x] #1662 - https://github.com/ruby/ruby/pull/8806

## Methods/parameters

* [x] #1663 - https://github.com/ruby/ruby/pull/8675
* [x] `AliasMethodNode` - https://github.com/ruby/ruby/pull/8311
* [x] #1664 - https://github.com/ruby/ruby/pull/8863
* [x] #1665 - https://github.com/ruby/ruby/pull/8725
* [x] #1666 - https://github.com/ruby/ruby/pull/8863
* [x] #1668 - https://github.com/ruby/ruby/pull/8863
* [x] #1669 - https://github.com/ruby/ruby/pull/8740
* [x] #1778 - https://github.com/ruby/ruby/pull/8863
* [x] `OptionalParameterNode` - https://github.com/ruby/ruby/pull/8322
* [x] #1670 - https://github.com/ruby/ruby/pull/8740
* [x] #1672 - https://github.com/ruby/ruby/pull/8863
* [x] #1779 - https://github.com/ruby/ruby/pull/8863
* [x] #1673 - https://github.com/ruby/ruby/pull/8863
* [x] `UndefNode` - https://github.com/ruby/ruby/pull/8311

## Pattern matching

* [x] `AlternationPatternNode` - https://github.com/ruby/ruby/pull/8535
* [x] #1674
* [x] #1675
* [x] #1676
* [ ] #1677
* [x] #1678
* [x] `MatchPredicateNode` - https://github.com/ruby/ruby/pull/8535
* [ ] #1679
* [x] `PinnedExpressionNode` - https://github.com/ruby/ruby/pull/8535
* [x] `PinnedVariableNode` - https://github.com/ruby/ruby/pull/8535

## Errors

* [x] `MissingNode`

**Comment by eregon** [comment]
This list by category is really nice, I wished for one like that recently, I would love to have this as part of the rdoc and/or some `.md` file, it's a great overview of nodes.
