### ISSUE TITLE
Parser options for either name_locs or names

### ISSUE THREAD

**Issue by jemmaissroff** [ruby/prism#1407]
Some nodes (eg `ClassVariableAndWriteNode`) have both a `name` field and a `name_loc` field. These are because it's helpful for some consumers (eg linters) to have the location, while it's helpful for other consumers (eg compilers) to have the name itself. Consumers need one, not both.

We could eventually expose a way for consumers to specify which field type they need. This would reduce overall memory impact of the parse tree by not storing all of these fields twice.

This isn't necessary for V1, and is most helpful if we decide to reduce memory since it'll introduce some otherwise unnecessary complexity.

**Comment by enebo** [comment]
@jemmaissroff I had suggested the notion of a profile between the two use-cases back when we discussed how syntax tools want offsets but compilers want line number.    The linting use case wants original source in memory and the compiler doesn't.  There are a number of different preferences between the two use-cases. It feels like two tools which overlap 80% trying to consume the same format.

**Comment by kddnewton** [comment]
Unfortunately a tool like rubocop needs both (I found out the hard way through https://github.com/kddnewton/parser-prism. I think since we're now not serialization the locations for JRuby/TruffleRuby and we could instead shrink the location struct, I think I'd like to close this one as not planned.
