### ISSUE TITLE
Statement sets

### ISSUE THREAD

**Issue by kddnewton** [ruby/prism#142]
When parsing a class, module, method, or `do` block definition, we need to handle the case of `rescue`/`ensure`/`else` clauses. For example:

```ruby
def foo
  1
rescue
  2
end
```

In this case the body isn't a statements node, it's actually a `BeginNode`. We should allow either one to be present in the method, depending on whether or not the additional keywords were used.

Note that we shouldn't attempt this until #141 and #135 are implemented.

**Comment by DmitryTsepelev** [comment]
Loooks like we also need #209 before it can happen
