### ISSUE TITLE
Properly handle nonassoc operators

### ISSUE THREAD

**Issue by kddnewton** [ruby/prism#1457]
https://bugs.ruby-lang.org/issues/19876

**Comment by makenowjust** [comment]
@mame Could you list up non-associative operators in Ruby?

Currently, Prism treats the following operators as non-associative.

- `in` and `=>` (in #1807)
- `..` and `...` (in #1837, and for some exceptions to end-less ranges in #2040)
- `==` and other equality operators (in #2079)

Are these complete?

**Comment by kddnewton** [comment]
Actually looking at `parse.y` I think this is completed now. https://github.com/ruby/ruby/blob/157e6c8a512968dc9f82d7f81606eeb3266cf6bb/parse.y#L2165-L2189

Thank you @makenowjust!
