### ISSUE TITLE
Method parameter order enforcement

### ISSUE THREAD

**Issue by kddnewton** [ruby/prism#153]
At the moment we allow any method parameter declarations to be in any position in the list. So for example `def foo(&bar, *baz)` is permitted by our parser but shouldn't be.

To maintain flexibility, we want to continue to allow the parameters to be parsed in any order, but we want to add errors if they are found to be incorrect. This allows the user to type them incorrectly and to have a nice experience, as opposed to just crashing.

**Comment by HParker** [comment]
Related, the compiler needs to know how many params are `pre` or `post` optional arguments for methods like,

```
def a(x, y = 1, z)
end
```
