### ISSUE TITLE
BlockParametersNode flag for ambiguous_param0

### ISSUE THREAD

**Issue by kddnewton** [ruby/prism#1538]
When you have a block like `foo { |a| }` the first parameter does autosplatting, and it's called `ambiguous_param0` in CRuby. You can tell it has this flag by running:

```
echo "foo { |a| }" | ruby -e 'pp RubyVM::InstructionSequence.compile($<.read).to_a'
```

which yields

```
["YARVInstructionSequence/SimpleDataFormat",
 3,
 2,
 1,
 {:arg_size=>0, :local_size=>0, :stack_max=>1, :node_id=>6, :code_location=>[1, 0, 1, 11], :node_ids=>[0, 0, -1]},
 "<compiled>",
 "<compiled>",
 "<compiled>",
 1,
 :top,
 [],
 {},
 [],
 [1,
  :RUBY_EVENT_LINE,
  [:putself],
  [:send,
   {:mid=>:foo, :flag=>4, :orig_argc=>0},
   ["YARVInstructionSequence/SimpleDataFormat",
    3,
    2,
    1,
    {:arg_size=>1, :local_size=>1, :stack_max=>1, :node_id=>4, :code_location=>[1, 4, 1, 11], :node_ids=>[-1, -1]},
    "block in <compiled>",
    "<compiled>",
    "<compiled>",
    1,
    :block,
    [:a],
    {:lead_num=>1, :ambiguous_param0=>true},
    [],
    [1, :RUBY_EVENT_B_CALL, [:putnil], :RUBY_EVENT_B_RETURN, [:leave]]]],
  [:leave]]]
```

you can see `ambiguous_param0` is in there. It _won't_ be in there if there are any other parameters or block locals. This should be implemented as a flag on `BlockParametersNode`.

**Comment by kddnewton** [comment]
@haldun feel like looking at this one? It's a little more involved

**Comment by haldun** [comment]
> It won't be in there if there are any other parameters or block locals

I am not sure if I understand the "block locals" part. I see `ambiguous_param0` for this code for example:

```
echo "foo { |a| b = 3 }" | ruby -e 'pp RubyVM::InstructionSequence.compile($<.read).to_a'
```

**Comment by kddnewton** [comment]
Ahh sorry @haldun I mean `foo { |;a| }` kind of locals

**Comment by haldun** [comment]
hmm, what am I missing here?

```
echo "foo { |a;c,d| }" | ruby -e 'pp RubyVM::InstructionSequence.compile($<.read).to_a' | grep ambiguous_param0
    {:lead_num=>1, :ambiguous_param0=>true},
```

**Comment by haldun** [comment]
I've tried different combinations, so it looks like the rule is basically 

`ambiguous_param0` is `true` if there is one and only one required parameter and there is no `*` or `***`

Also found out this reference https://github.com/ruby/ruby/blob/ce094e8556014b5c1f175ff7c1b881339ad84a41/vm_core.h#L415C1-L415C59

**Comment by eregon** [comment]
So it's one of the things checked for whether to autosplat, when it's true there no autosplat:
https://github.com/ruby/ruby/blob/071df40495e31f6d3fd14ae8686b01edf9a689e3/vm_args.c#L645
Given it's only a small part of the autosplat check I think it doesn't make to expose this in Prism.

**Comment by kddnewton** [comment]
@eregon we would like to expose this information both for CRuby to use so that it doesn't have to calculate it and so that other consumers can use it. The name is consistent with how CRuby uses it and with documentation, I think it's fine.

This flag is not unrelated to block autosplatting, it is explicitly what autosplatting does. If you take `ambiguous_param0` out of CRuby you get this:

```ruby
[[1, 2], [3, 4], [5, 6]].each do |ary|
  p ary
end
# 1
# 3
# 5
```

with it in CRuby you get this:

```ruby
[[1, 2], [3, 4], [5, 6]].each do |ary|
  p ary
end
# [1, 2]
# [3, 4]
# [5, 6]
```

It's not dead code, it functions as it's designed.

**Comment by kddnewton** [comment]
If you don't want to use the flag that's fine, but we're going to use it in CRuby. You can absolutely ignore it in TruffleRuby.

**Comment by eregon** [comment]
It's trivial to compute:
https://github.com/ruby/ruby/blob/071df40495e31f6d3fd14ae8686b01edf9a689e3/compile.c#L2094-L2097
Why trying to do the job of the compiler in Prism here?

The naming contradicts the values of Prism, as written in https://kddnewton.com/2023/12/05/advent-of-prism-part-5#naming.
Also I don't how I can say this nicely but `ambiguous_param0` is some ugly unclear weird confusing abbreviation, like worse than `zsuper` or `fcall`.
It's just some obscure name, which is I hope you can agree unnecessary to be part of the tree, because trivially redundant with information already available in that node.

**Comment by eregon** [comment]
Do you really think a tool using Prism would use this flag?
I can only imagine confusion ("WTH is this?") and incorrect usage, no actual value.

**Comment by kddnewton** [comment]
> completely arbitrary field in Prism API for no reason

I've listed the reasons above.

Either way, I don't feel like dealing with this.

**Comment by eregon** [comment]
@kddnewton I am sorry for the inflammatory comments, I did not mean to offend or criticize, I wanted to raise the point that this flag looks like a CRuby implementation detail subject to change and a suboptimal name.
I want the Prism API to be as good as possible, I am sure you do too, to have the maximum chances of success and adoption.
I'll work on expressing my concerns more productively going forward.
