### ISSUE TITLE
parse/parse_serialize needs explicit encoding metadata

### ISSUE THREAD

**Issue by enebo** [ruby/prism#1639]
This eval should print US-ASCII and not UTF-8:

```ruby
#coding: US-ASCII

p eval("__ENCODING__")
```

parse_serialize needs to pass in an explicit encoding (US-ASCII) as metadata so we can specify the encoding of the source bytes.

**Comment by eregon** [comment]
It's stored in the Loader: https://github.com/ruby/prism/blob/3b70a9dfceb86d66dc46ba355fe8ec4e9c1e39a6/templates/java/org/prism/Loader.java.erb#L82
If you subclass it, e.g. to implement `bytesToName()` then you can access it there.

And it's already part of the serialization format: https://github.com/ruby/prism/blob/main/docs/serialization.md#structure

**Comment by eregon** [comment]
Ah but the field is `private`, my bad, we could change it to `protected` of course, could you make a PR if that's enough for what you need?

**Comment by eregon** [comment]
> This issue is that the eval parse must pass in that its encoding is explicitly US-ASCII. I do not see a mechanism for that. I think we can just pass in another section to metadata for that.

Right that makes sense, it's indeed missing from https://github.com/ruby/prism/blob/main/docs/serialization.md#apis.
The issue description was rather sparse, it would be nice to update it with that.

**Comment by enebo** [comment]
@eregon I tried rearranging that sentence to hopefully be more clear.
