### ISSUE TITLE
Fix prettyprinting in C API

### ISSUE THREAD

**Issue by jemmaissroff** [ruby/prism#1681]
We have done a lot of work to make the pretty printing look nice in the Ruby API. We should mirror this in the `pm_print_node` function in the C API so that C can also benefit from the nice printing

**Comment by eregon** [comment]
FWIW there is also pretty printing for Java which is sort of similar to the Ruby one but much simpler: https://github.com/ruby/prism/blob/f7ff3a3fdd720c9896ebf789dbb5d79dc639f9e5/templates/java/org/prism/Nodes.java.erb#L279-L326
That might be a good fit for C and easier to port than the more complex logic used in Ruby.
