### ISSUE TITLE
StringNode needs an encoding field

### ISSUE THREAD

**Issue by enebo** [ruby/prism#1703]
If I have Ruby source like:

```ruby
# coding: US-ASCII

a = "\u{C0}"
p a.encoding
```

The string assigned to a will recognize it contains UTF-8 escape sequence and it will mark it with that encoding even though the file wants strings to be US-ASCII.   Since prism unescapes this string it already knows its encoding and should provide it.  This is probably true of any unescaped data too?

**Comment by kddnewton** [comment]
It is always going to become UTF-8? Could this just be a flag?

**Comment by enebo** [comment]
@kddnewton I think there are only two additional encodings: ASCII-8BIT (binary) and UTF-8:

```ruby
# coding: US-ASCII

a = "\u{C0}"
p a.encoding

b = "\xef"
p b.encoding

c = "normal"
p c.encoding
```

output:
```text
#<Encoding:UTF-8>
#<Encoding:ASCII-8BIT>
#<Encoding:US-ASCII>
```

So I think flags would be cheaper than an encoding field.

**Comment by kddnewton** [comment]
This yields some very surprising results:

```ruby
Encoding.list.each do |encoding|
  next if encoding.dummy? || !encoding.ascii_compatible?

  puts encoding.name

  ["x", "\\x0", "\\xFF", "\\u{0}", "\\u{FF}"].each do |string|
    puts "  %-10s %s" % [string.inspect, eval("# encoding: #{encoding.name}\n\"#{string}\"").encoding.inspect]
  end
end
```

**Comment by enebo** [comment]
@kddnewton So binary and UTF-8 are special but binary is only special in us-ascii.   As for UTF-8 I guess past some value it decides to use it rather than the native encoding?  So one generic rule for UTF-8 and one specific rule for US-ASCII?  Or will using a wider range of chars yield more fun results?

**Comment by kddnewton** [comment]
The rules appear to be the following:

## ASCII-8BIT

* `\x` no change
* `\u{00}-\u{7F}` no change
* `\u{80}+` change to UTF-8

## UTF-8

No change

## US-ASCII

* `\x00-\x7F` - no change
* `\x80-\xFF` - change to ASCII-8BIT
* `\u{00}-\u{7F}` - no change
* `\u{80}+` change to UTF-8

## Others

* `\x` no change
* `\u{00}-\u{7F}` no change
* `\u{80}+` change to UTF-8

**Comment by kddnewton** [comment]
I'll check combinations of the escapes next...

**Comment by enebo** [comment]
@kddnewton yeah another thing I am unsure about is broken strings.  Mixing invalid bytes into an encoding will get marked broken by cr but I don't recall if it can affect encoding during parse or not.  Strings are tough :smiling_face_with_tear:

**Comment by kddnewton** [comment]
Looks like it raises syntax errors in _some_ cases but not in others.

**Comment by kddnewton** [comment]
Oh man it gets worse... for some reason `\x00\x00` in every encoding appears to convert to `UTF-8`?

**Comment by kddnewton** [comment]
Oh god it's so bad..


```ruby
escapes = [
  "\\x00",
  "\\x7F",
  "\\x80",
  "\\xFF",
  "\\u{00}",
  "\\u{7F}",
  "\\u{80}",
]

escapes.concat(escapes.product(escapes).map(&:join))

Encoding.list.each do |encoding|
  next if encoding.dummy? || !encoding.ascii_compatible?

  puts encoding.name

  escapes.each do |escape|
    result =
      begin
        eval("# encoding: #{encoding.name}\n\"#{escape}\"").encoding.name
      rescue SyntaxError
        "SyntaxError"
      end

    puts "  %-30s %s" % [escape.inspect, result]
  end
end
```

**Comment by kddnewton** [comment]
Okay, I've done a lot of investigation into this, and I think we need every `type: string` field to additionally supply its encoding because they can all differ from the default encoding of the file.

**Comment by eregon** [comment]
Given there are only 6 `type: string` in https://github.com/ruby/prism/blob/main/config.yml that seems fine.
I'm not sure it's needed for Regexp and Symbol literals, but it's only a one byte overhead anyway if we serialize encodings as an index (and there are < 256 encodings), so it seems simpler to just do it for all `type: string` indeed.

**Comment by enebo** [comment]
I think based on @kddnewton comments above where he plays with various characters in strings we can get away with a flag for the encoding.  We have four states: file encoding, UTF-8, US-ASCII, ASCII-8BIT .     This may still take a whole byte but I don't think it needs to generalize to storing arbitrary encodings.  Regexp and symbols both can also follow rules based on this (e.g. symbols are US-ASCII is clean 7-bit, regexps with `\u` are UTF-8) so I do not think there is a waste problem for those.

**Comment by eregon** [comment]
@kddnewton Do you plan to work on this soon? (any ETA?)
Could you share how you think it should be done, i.e. flags or an extra byte for encoding in `type: string` fields?

For context, we want to switch to Prism for TruffleRuby 24.0 which has a feature freeze of February 1st, so we would need blocking issues like this one (and https://github.com/ruby/prism/issues/1715 which @andrykonchin will try to fix) to be solved at latest a week before that (and earlier the better and less stressful).

**Comment by kddnewton** [comment]
It will be two flags: `ENCODING_ASCII_8BIT` and `ENCODING_UTF_8`. It will be assumed if neither of these flags are set that the string encoding matches the default (UTF-8 if no encoding comment is found, the value of the comment otherwise).

I'm hoping to have it done this week. Worst case, the week after.

**Comment by kddnewton** [comment]
This is now done. I'm going to open separate issues for the remnants: symbols and regex
