### ISSUE TITLE
Consider creating AttributeAssignNode or a flag on CallNode

### ISSUE THREAD

**Issue by enebo** [ruby/prism#1715]
I just ran across the semantic wrinkle that a CallNode `a=(4)` will return 4 and not whatever is the last value in `a=()`.  In current parsers we make a special node (AttrAsgnNode) for this.  We can check to see if last value in a name is '=' and change semantics but this feels hacky.

One solution is to make a flag we can check to see if it is an assignment but this will make call node processing a tiny bit more complicated (we have to retain value -- simpler with temp vars in JRuby but perhaps more juggling for stack-based compiler in MRI).

Another solution is to make a new node type (e.g. AttributeAssignNode) like current parsers.  The complication here is we are still proliferating more node types which are call nodes.

The fact that calls already span more than one node would make me favor a new node but I know not everyone likes the node proliferation.  I am ok with either solution but I don't want to have to examine the method name and I think for newer programmers they would be completely lost until they learned about this semantic difference.

**Comment by eregon** [comment]
+1 for the flag, it would be convenient.

Although currently in truffleruby we are just using `methodName.endsWith("=")` for this, isn't that enough/correct? It doesn't seem particularly expensive.

**Comment by enebo** [comment]
@eregon if you are writing some tool against this AST you have to know this behavior.  I knew this and I still hadn't realized it until I saw a test case fail.  I think the tree should spell it out somehow.

A third option is to generate a method which does endsWidth so we do not need to store the flag but the node has a method documenting this.  I don't think we have a mechanism for this via config.yml so that would be a significant feature (and how do we do that cross-platform?).

**Comment by enebo** [comment]
@eregon As it turns out `endsWith` is not enough for this to work.  You can define `==` and `===`.  So this check is a little more involved.

**Comment by eregon** [comment]
Ah, good point about `==` and `===`! cc @andrykonchin

**Comment by enebo** [comment]
@eregon  Also <, >, and !.

**Comment by tompng** [comment]
For `[]=` method, method name check is not enough because
```ruby
a = []; def a.[]=(k,v); 42 end
a[1] = 2 # will return 2
a.[]=(1, 2) # will return 42
```
It's both CallNode(name: `:[]=`) call_operator_loc, message_loc, opening_loc and closing_loc differs.

**Comment by eregon** [comment]
This caused a pretty weird bug while trying to use Prism to load the TruffleRuby core library, i.e., `:a == :b` would return true, because `==` ends with `=` and so it would treat it as an attribute assignment which returns the value.

@kddnewton Could you prioritize adding this necessary flag?
AFAIK no compiler based on Prism can be correct until that is done (or needs very ugly workarounds).

**Comment by kddnewton** [comment]
I will prioritize it the best I can, but there is a lot going on right now. In the meantime you can copy Tom's work, which is already functioning just fine: https://github.com/enebo/jruby/blob/2fc1cf1babf48a985f400b69f815e39f921e8825/core/src/main/java/org/jruby/ir/builder/IRBuilderPrism.java#L1831-1835.

**Comment by eregon** [comment]
Thanks for the link, I'll try that workaround for now.
It's not fully correct though, as @tompng showed above, so it will for sure fail some specs.

**Comment by enebo** [comment]
@eregon I will check on whether it fails anything (I do not recall anything failing running specs) and if it doesn't add something but fwiw is this behavior used by anyone anywhere?  We obviously plan on fixing this issue but this has to be very uncommon.

**Comment by eregon** [comment]
I think that's correct.
The last one should be `foo.[]=(bar, 1)` (missing `=`).
I.e., if the `=` separates the value from other arguments it's attribute assignment, and the return value is the value/RHS of that assignment, not what the method call returns.

**Comment by eregon** [comment]
`foo.bar=(1)` is attribute assignment yes.
It's easy to check in IRB:
```
irb(main):001:0> foo = Object.new
irb(main):006:0> def foo.bar=(v); 42; end
irb(main):007:0> foo.bar=1
=> 1
irb(main):008:0> foo.bar=(1)
=> 1
irb(main):009:0> foo.send(:bar=, 1)
=> 42
irb(main):010:0> def foo.[]=(k,v); 42; end
=> :[]=
irb(main):011:0> foo[1] = 2
=> 2
irb(main):013:0> foo.[]=(1,2)
=> 42     
```

**Comment by kddnewton** [comment]
I decided to roll with an attribute for this because the nodes are the exact same otherwise. It's kind of annoying that you'll have to check the flag to know what the return value is, but I think it would be _more_ annoying for other consumers like linters/formatters to have to handle multiple call types. Sorry if this is less than ideal.

**Comment by eregon** [comment]
A flag is definitely better for this :+1: , it's a very minor modification of behavior of CallNode, thanks for the adding it!
