### ISSUE TITLE
Consider adding a Target counterpart for `CallNode`

### ISSUE THREAD

**Issue by andrykonchin** [ruby/prism#1723]
It seems to me reasonable (at least for the sake of consistency) to have a target node for a method call, e.g. CallTargetNode.

It would be helpful to differentiate (without checking the context) a simple method call from a synthetic call node that is missing the last argument (that will be assigned in runtime). Such a target call node might be present in the `rescue` operator and multi-assignment and could be either attribute assignment (`a.foo, b = []`) or reference assignment (`a[:foo], b = []`).

Does it make sense?

**Comment by eregon** [comment]
Right, this seems a perfect fit given the other `*TargetNode` used in such a case.

**Comment by kddnewton** [comment]
Okay, let's do this one.
