### ISSUE TITLE
You can assign to local variables outside the scope with regex

### ISSUE THREAD

**Issue by kddnewton** [ruby/prism#1758]
Right now we only have a list of constant IDs for match write nodes, but this doesn't convey the depth. (It actually does add the locals to the correct scope though, so this is more of an enhancement than a bug.)

As an example:

```ruby
a = 1
tap { /(?<a>)/ =~ to_s }
```

This will yield a match write node with `locals: [:a]` with no knowledge of depth. We should replace this `constant[]` with a `node[]` and use local variable target nodes instead.

**Comment by enebo** [comment]
I actually walk my static scope stack to reacquire depth.   I think it makes more sense to use Nodes here as well especially if you are not compiling code but merely using it as a syntax tool.
