### ISSUE TITLE
Add information about proc's numbered parameters count

### ISSUE THREAD

**Issue by andrykonchin** [ruby/prism#1762]
It would be helpful to have numbered parameters count (in proc) provided.

A proc with numbered parameters should be handled in a bit different way and we cannot rely on `ParametersNode` to have actual information about proc's arity and parameter names. We can rely only on `BlockNode#locals` and check if there are names like `_` + digit (1-9) and there are no `BlockParametersNode` or `ParametersNode`. So number of such locals (or the largest digit) would tell us how many numbered parameters are there.

It will be nice to have the numbered parameters count to be provided explicitly, e.g. as a `char`/`byte` fields. Also it might be simpler to have a separate node class (e.g. `NumberedParametersNode`) to use instead of `ParametersNode` in such a case. This way `NumberedParametersNode` would not contain numerous fields like `requireds`, `optionals` etc and have only one integer field.

**Comment by enebo** [comment]
@andrykonchin this is even a little bit grosser on detection:

```ruby
proc { |_9a| p _9a }.call("a")
```

**Comment by kddnewton** [comment]
Right, I think it's `^_\d$`.

**Comment by enebo** [comment]
@kddnewton please prevent this tragedy :smiley: 

```java
   public int highestNumberedParameter() {
        if (type != Type.BLOCK) return 0;

        int biggest = 0;

        for (String name: variableNames) {
            if (name.matches("_\\d+$")) biggest = Integer.parseInt(name.substring(1, name.length()));
        }

        return biggest;
    }
```

**Comment by kddnewton** [comment]
Yeah, I suppose I had to do that as well when translating to whitequark/parser. https://github.com/kddnewton/parser-prism/blob/cff12ee1955c651659b5230dc562aa5a2d8fbcc3/lib/parser/prism/compiler.rb#L911-L913. We can work on this.

**Comment by kddnewton** [comment]
Nope! :) fortunately it only allows up to `_9` so you should be able to get rid of the `+`

**Comment by eregon** [comment]
Currently the `block.parameters` is nil, but that seems not great given the block does have parameters, they are just numbered vs named.

How about  using a BlockParametersNode too with an array of `RequiredParameterNode` with names _1, _2, etc? That seems best to me.
One thing is those nodes wouldn't have a corresponding location in the source, but maybe we can just give them startOffset=0 length=0, or the whole block location maybe?

Or maybe a `NumberedParametersNode` or so, which would e.g. contain how many there are?

Currently the `block.parameters` is nil, which is inconvenient for compilation:
```
$ bin/parse -e 'foo { _2 }'   
@ ProgramNode (location: (1,0)-(1,10))
├── locals: []
└── statements:
    @ StatementsNode (location: (1,0)-(1,10))
    └── body: (length: 1)
        └── @ CallNode (location: (1,0)-(1,10))
            ├── receiver: ∅
            ├── call_operator_loc: ∅
            ├── message_loc: (1,0)-(1,3) = "foo"
            ├── opening_loc: ∅
            ├── arguments: ∅
            ├── closing_loc: ∅
            ├── block:
            │   @ BlockNode (location: (1,4)-(1,10))
            │   ├── locals: [:_1, :_2]
            │   ├── parameters: ∅
            │   ├── body:
            │   │   @ StatementsNode (location: (1,6)-(1,8))
            │   │   └── body: (length: 1)
            │   │       └── @ LocalVariableReadNode (location: (1,6)-(1,8))
            │   │           ├── name: :_2
            │   │           └── depth: 0
            │   ├── opening_loc: (1,4)-(1,5) = "{"
            │   └── closing_loc: (1,9)-(1,10) = "}"
            ├── flags: ∅
            └── name: :foo
```

Compared to:
```
$ bin/parse -e 'foo { |a,b| b }'
@ ProgramNode (location: (1,0)-(1,15))
├── locals: []
└── statements:
    @ StatementsNode (location: (1,0)-(1,15))
    └── body: (length: 1)
        └── @ CallNode (location: (1,0)-(1,15))
            ├── receiver: ∅
            ├── call_operator_loc: ∅
            ├── message_loc: (1,0)-(1,3) = "foo"
            ├── opening_loc: ∅
            ├── arguments: ∅
            ├── closing_loc: ∅
            ├── block:
            │   @ BlockNode (location: (1,4)-(1,15))
            │   ├── locals: [:a, :b]
            │   ├── parameters:
            │   │   @ BlockParametersNode (location: (1,6)-(1,11))
            │   │   ├── parameters:
            │   │   │   @ ParametersNode (location: (1,7)-(1,10))
            │   │   │   ├── requireds: (length: 2)
            │   │   │   │   ├── @ RequiredParameterNode (location: (1,7)-(1,8))
            │   │   │   │   │   └── name: :a
            │   │   │   │   └── @ RequiredParameterNode (location: (1,9)-(1,10))
            │   │   │   │       └── name: :b
            │   │   │   ├── optionals: (length: 0)
            │   │   │   ├── rest: ∅
            │   │   │   ├── posts: (length: 0)
            │   │   │   ├── keywords: (length: 0)
            │   │   │   ├── keyword_rest: ∅
            │   │   │   └── block: ∅
            │   │   ├── locals: (length: 0)
            │   │   ├── opening_loc: (1,6)-(1,7) = "|"
            │   │   └── closing_loc: (1,10)-(1,11) = "|"
            │   ├── body:
            │   │   @ StatementsNode (location: (1,12)-(1,13))
            │   │   └── body: (length: 1)
            │   │       └── @ LocalVariableReadNode (location: (1,12)-(1,13))
            │   │           ├── name: :b
            │   │           └── depth: 0
            │   ├── opening_loc: (1,4)-(1,5) = "{"
            │   └── closing_loc: (1,14)-(1,15) = "}"
            ├── flags: ∅
            └── name: :foo
```
