### ISSUE TITLE
Locations report incorrect `end_column` when emoji are present

### ISSUE THREAD

**Issue by joeldrapper** [ruby/prism#1770]
I don’t know if this is a bug or a feature, but the reported `end_column` location values are incompatible with Ruby’s `String#[]` offsets.

For example, `Prism` reports this as `6`:

```ruby
Prism.parse("# 👋").comments.first.location.end_column
```

but Ruby reports `"# 👋".length` as `3`.

This presents a challenge if you need to use Prism locations for String insertion offsets in Ruby, because, as far as I can tell, there’s no `String#insert_at_byte` method in Ruby.

**Comment by kddnewton** [comment]
Yeah this is by design, the offsets are purposefully byte offsets. We rely on that for a bunch of APIs unfortunately.

**Comment by kddnewton** [comment]
I would suggest converting to an array of bytes and then inserting your additions.

**Comment by kddnewton** [comment]
Or build a cache of byte offset to character offset.

**Comment by joeldrapper** [comment]
Thanks @kddnewton. I wasn't sure if there might be a way to expose the ruby string offsets in the Ruby API. Using an array of bytes makes sense and seems to work for my use case. 🙏

**Comment by kddnewton** [comment]
All that being said, maybe we should provide API for returning character offsets as well. We could probably do that lazily for those that need it.

**Comment by joeldrapper** [comment]
For now, I’m doing something like this to convert the locations to Ruby-compatible Array and String offsets.

```ruby
@annotations << [
  symbol,
  location.start_line - 1,
  lines[location.start_line - 1]
    .byteslice(0, loc.start_column)
    .force_encoding("UTF-8")
    .length
]
```

I’ve found it’s a useful layer to subtract `1` from the `start_line`, too, which you almost always want to do unless you display it to a human.

**Comment by kddnewton** [comment]
I wouldn't necessarily convert it directly into `UTF-8`, as the source could be any number of encodings.
