### ISSUE TITLE
Support a maximum depth to protect against malicious payloads

### ISSUE THREAD

**Issue by kddnewton** [ruby/prism#1774]
Bison supports `YYMAXDEPTH` [(docs)](https://www.gnu.org/software/bison/manual/html_node/Memory-Management.html), we should do something similar so that we can provide a better experience than a `SystemStackError` or equivalent.

**Comment by haldun** [comment]
I have couple of question about this:

- Is `parser_t` a good place to keep the level of recursion?
- Is testing whether we hit the limit in `parse_expression` enough, or do we need to guard against this in any other functions?
- What should the parser do when the limit is hit?

**Comment by HeyNonster** [comment]
The depth in Bison defaults to `10000` but in #3083 Prism's default depth was set to `1000`. `parse.y` has a much higher limit and we were curious if the discrepancy was an intentional choice. 

cc: @bquorning

**Comment by kddnewton** [comment]
Whoops, that's just a mistake. I misread the number of 0s in the bison docs. Feel like a contribution? We need to update `defines.h`.

Out of curiosity did you actually hit this depth? (I'm hoping I didn't break your app.)

**Comment by bquorning** [comment]
We actually did hit this limit, when rendering some view templates in Rails. 😅

We'll look into fixing defines.h tomorrow.

**Comment by kddnewton** [comment]
Ahh dang sorry about that! If you don't have the time tomorrow no worries I can do it. But I'll give you a day to get a contribution in :)

**Comment by bquorning** [comment]
Eh, nothing that a rollback couldn’t fix. Don’t worry about it.

PR ready at #3413.

**Comment by HeyNonster** [comment]
Agreed, it wasn't much of a hassle. Thank you for all your great work on Prism!

**Comment by kddnewton** [comment]
Nice. I will ask the branch maintainer for 3.4 to backport this so that it goes out in the next patch release (hopefully).
