### ISSUE TITLE
Rust crate packaging

### ISSUE THREAD

**Issue by turboladen** [ruby/prism#1786]
It's been some months since I've been in this neck of the woods, and it seems lots has changed (which is exciting)! I just went to give a shot using the `prism` crate in a project and I get build failures with `prism-sys` (`vendor_dir` doesn't exist). Is this expected? After poking at it, it _looks_ like `prism-sys` expects you to build it from the prism repo/workspace (is that right?). ...which makes me wonder about the current thoughts on/state of crate packaging.

IIRC, there were some discussions about packaging the crates, but I didn't find anything in the Issues list, so I thought I'd ask before I started poking at it more:

* Is my experience the currently expected behavior?
* Have there been any more discussions on the topic? 
* Do you all have ideas floating around about how you'd like to approach this (or maybe approaches you want to avoid)? 

---

FWIW, here's the trace I get when trying to pull in `prism` to a project:

```
   Compiling prism v0.17.1 (https://github.com/ruby/prism#4a459b23)
   Compiling prism-sys v0.17.1 (https://github.com/ruby/prism#4a459b23)
error: failed to run custom build command for `prism-sys v0.17.1 (https://github.com/ruby/prism#4a459b23)`

Caused by:
  process didn't exit successfully: `/Users/steve.loveless/Development/projects/ruby_analyzer/target/debug/build/prism-sys-78c8b4886147ff3d/build-script-main` (exit status: 101)
  --- stderr
  thread 'main' panicked at /Users/steve.loveless/.cargo/git/checkouts/prism-964b59ab8481264d/4a459b2/rust/prism-sys/build/vendored.rs:8:5:
  Prism source directory does not exist, expected: /Users/steve.loveless/.cargo/git/checkouts/prism-964b59ab8481264d/4a459b2/rust/prism-sys/vendor/prism-0.17.1
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by kddnewton** [comment]
Hey @turboladen!

It's not so much the expected behavior as we just haven't figured it out yet. Ideally I'd like to release everything to cargo and have it be all packaged up correctly, I'm just not entirely sure how to do that yet.

I'm assuming you're pointing to the github directly in cargo? Maybe we need additional build options set up in order to properly handle that.

Overall the answer is we just don't know yet!

**Comment by turboladen** [comment]
Ok, great! I'm interested in digging to this, so I might do that in the near future. Just wanted to make sure I wasn't gonna go off on some known undesirable path. 🙂 

And yeah, initially I pointed my repo directly to the prism GH repo, then tried manually pulling the repo and pointing to that locally--same results.

**Comment by turboladen** [comment]
Hmm, turns out that I can't build `prism-sys` from a vanilla clone of the prism repo, so it seems I'm running into another problem that's unrelated to packaging.

**Comment by kddnewton** [comment]
What issues are you seeing?

**Comment by turboladen** [comment]
from `rust/prism-sys/`:
```
prism/rust/prism-sys on  main [!] is 📦 v0.17.1 via 💎 v3.2.2 via 🦀 v1.73.0 on ☁️  (us-west-1) took 9s
❯ RUST_BACKTRACE=1 cargo c --features vendored
   Compiling prism-sys v0.17.1 (/Users/steve.loveless/Development/not_my_projects/prism/rust/prism-sys)
error: failed to run custom build command for `prism-sys v0.17.1 (/Users/steve.loveless/Development/not_my_projects/prism/rust/prism-sys)`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `/Users/steve.loveless/Development/not_my_projects/prism/rust/prism-sys/target/debug/build/prism-sys-62374b943016d99e/build-script-main` (exit status: 101)
  --- stderr
  thread 'main' panicked at build/vendored.rs:8:5:
  Prism source directory does not exist, expected: /Users/steve.loveless/Development/not_my_projects/prism/rust/prism-sys/vendor/prism-0.17.1
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
     1: core::panicking::panic_fmt
               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
     2: build_script_main::vendored::build
     3: build_script_main::main
     4: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by kddnewton** [comment]
Yeah it looks like @ianks built `rake cargo:build` in https://github.com/ruby/prism/commit/93f7126bc62 for that purpose. I think that would have to be run before attempting to publish.

**Comment by Speak2Erase** [comment]
When cargo checks out git dependencies, it checks out the entire git repository. It'd be possible for prism-sys to fallback to `$CARGO_MANIFEST_DIR/../../` if there is no vendor directory present, allowing prism-sys to be used from a git dependeny

**Comment by ngroman** [comment]
I'll admit that I'm not a crates expert but I think I've come up with a possible solution that was able to `--dry-run`. In this case I'm centralize the `Cargo.lock` files and use a cargo workspace.

**Comment by Speak2Erase** [comment]
I can try, but it'll likely require rake to be installed on the user's system to work properly

The best solution imho is to add a Cargo.toml at the root of the repository (should make publishing and development easier) and publish prism on crates.io

**Comment by kddnewton** [comment]
This is now released. I believe we should be good, let me know if there are more issues.
