### ISSUE TITLE
Error in regexp provides invalid startoffset in ParseError

### ISSUE THREAD

**Issue by enebo** [ruby/prism#1793]
```text
parse -e '/\c/'
Errors:
[#<Prism::ParseError @message="Expected a closing delimiter for the regular expression" @location=#<Prism::Location @start_offset=4 @length=0 start_line=1>>]

AST:
@ ProgramNode (location: (1,0)-(1,4))
├── locals: []
└── statements:
    @ StatementsNode (location: (1,0)-(1,4))
    └── body: (length: 1)
        └── @ InterpolatedRegularExpressionNode (location: (1,0)-(1,4))
            ├── opening_loc: (1,0)-(1,1) = "/"
            ├── parts: (length: 1)
            │   └── @ StringNode (location: (1,1)-(1,4))
            │       ├── flags: ∅
            │       ├── opening_loc: ∅
            │       ├── content_loc: (1,1)-(1,4) = "\\c/"
            │       ├── closing_loc: ∅
            │       └── unescaped: "\\x0F"
            ├── closing_loc: (1,4)-(1,4) = ""
            └── flags: ∅
```

Seems startOffset should be 0 and not one past last char.

**Comment by enebo** [comment]
I should add this throws when we try and determine linenumber from startoffset and it is off the source byte array so we assert (in Java but I imagine it will be that or worse in C).

**Comment by kddnewton** [comment]
Hmm. There are quite a few error messages that will be right at the end of the file. You'll see 0-length errors pointing to the last offset whenever you have unterminated string-like stuff or missing ends etc. Or for missing nodes, like `a +` you'll get an error right at the end as well. Changing all of these kinds of error locations is possible, but is going to be a much bigger lift than it might seem.

Could we change the Java line number calculation to be `<= end`?

**Comment by enebo** [comment]
@kddnewton I had written that exact suggestion in and removed it because I wasn't sure I knew enough about whether it indexed more than what would be an imaginary EOF offset. That works for me.

**Comment by kddnewton** [comment]
Nice, would you be able to take a look at that? I don't really know what I'm doing on the Java side.

**Comment by enebo** [comment]
@kddnewton yeah ok.  I don't think I am working tomorrow (holiday) but I will get to this sooner than later.
