### ISSUE TITLE
Data comment (PM_COMMENT___END__) should make it into serialization

### ISSUE THREAD

**Issue by enebo** [ruby/prism#1824]
Data comment (PM_COMMENT___END__) should make it into serialization.

Currently these are put into the same list as ordinary comments and serialization omits them via:

```c
<%- unless Prism::SERIALIZE_ONLY_SEMANTICS_FIELDS -%>
    pm_serialize_comment_list(parser, &parser->comment_list, buffer);
<%- end -%>
```

We definitely only want the DATA comment (stuff after __END__) but it feels like this is not even really a comment and perhaps should be something else?

**Comment by eregon** [comment]
Maybe this could be stored as an offset in ParseResult or ProgramNode or so?
Because then the contents is simply from that offset until the end-of-file.
Or it could be a node of course.

Agreed `__END__`/`DATA` is not often treated as a comment, so it might be best to be a separate thing anyway.

**Comment by kddnewton** [comment]
Yeah I agree, I think it should be a separate field on parse result.
