### ISSUE TITLE
Compilation failure on MacOS Sonoma

### ISSUE THREAD

**Issue by JonathanMonahan** [ruby/prism#1827]
Gem version 0.17.1 fails to compile on MacOS Sonoma:
```
% gem install prism
Fetching prism-0.17.1.gem
Building native extensions. This could take a while...
ERROR:  Error installing prism:
	ERROR: Failed to build gem native extension.

    current directory: /Users/jonathan/.gem/ruby/3.2.2/gems/prism-0.17.1/ext/prism
/Users/jonathan/.rubies/ruby-3.2.2/bin/ruby extconf.rb
checking for whether -fvisibility=hidden is accepted as CFLAGS... yes
compiling build/static/diagnostic.o
compiling build/static/token_type.o
compiling build/static/prettyprint.o
compiling build/static/util/pm_strpbrk.o
compiling build/static/util/pm_char.o
compiling build/static/util/pm_memchr.o
compiling build/static/util/pm_list.o
compiling build/static/util/pm_strncasecmp.o
compiling build/static/util/pm_state_stack.o
compiling build/static/util/pm_string.o
compiling build/static/util/pm_newline_list.o
compiling build/static/util/pm_string_list.o
compiling build/static/util/pm_buffer.o
compiling build/static/util/pm_constant_pool.o
compiling build/static/serialize.o
serialize.c.erb:290:30: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
    pm_options_t options = { 0 };
                             ^
                             {}
serialize.c.erb:325:30: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
    pm_options_t options = { 0 };
                             ^
                             {}
2 errors generated.
make: *** [build/static/serialize.o] Error 1
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/jonathan/.rubies/ruby-3.2.2/bin/$(RUBY_BASE_NAME)
	--enable-debug-mode-build
	--disable-debug-mode-build
	--enable-static
	--disable-static
extconf.rb:78:in `system': Command failed with exit 2: make (RuntimeError)
	from extconf.rb:78:in `block in build_target_rubyparser'
	from extconf.rb:72:in `chdir'
	from extconf.rb:72:in `build_target_rubyparser'
	from extconf.rb:68:in `build_static_rubyparser'
	from extconf.rb:42:in `configure_rubyparser'
	from extconf.rb:20:in `configure'
	from extconf.rb:136:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/jonathan/.gem/ruby/3.2.2/extensions/x86_64-darwin-23/3.2.0-static/prism-0.17.1/mkmf.log

extconf failed, exit code 1
```

Gem version 0.16.0 compiles successfully on MacOS Sonoma:
```
% gem install prism --version 0.16.0
Fetching prism-0.16.0.gem
Building native extensions. This could take a while...
Successfully installed prism-0.16.0
Parsing documentation for prism-0.16.0
Installing ri documentation for prism-0.16.0
Done installing documentation for prism after 2 seconds
1 gem installed
```

**Comment by eregon** [comment]
Oh interesting, this even fails on the most recent macOS, I thought it was only on older macOS like Mojave: https://github.com/ruby/prism/pull/1813 (and https://github.com/ruby/prism/pull/1706).

Which XCode version do you have, and what's your `clang --version`?

What's odd is in CI in GitHub Actions it works fine (on macOS Monterey): https://github.com/ruby/prism/actions/runs/6859596120/job/18652123881

Maybe `{ 0 }` initialization when there is a nested struct field is not standard C99? I'm not sure.
IMO `{ 0 }` often feels hacky so it'd be best to initialize explicitly all fields of such structs on stack.
Or not initialize it and instead let the compiler error if a field is used uninitialized.

**Comment by eregon** [comment]
A possible fix is to use memset (and let the compiler optimize that): https://stackoverflow.com/a/11152208/388803
From `-O1` there is no call to memset and it's the same as explicit initialization: https://godbolt.org/z/3frrch53v

Given that things like `pm_options_t options = { { 0 }, 0, { 0 }, 0, 0, 0, 0 };` doesn't seem nice or particularly maintainable.

**Comment by eregon** [comment]
Another way is just adding `-Wno-missing-braces` to the Makefile, if this seems buggy behavior and `{ 0 }` is supposed to be C99 standard (which https://lore.kernel.org/git/xmqq7d4kp8l6.fsf@gitster.g/t/ seems to claim, but not sure it's true).
I think memset() is a nicer and clearer solution (IMO it's weird syntax to write one zero and expect to init all fields, should be either `{}` then or explicitly init all).

**Comment by JonathanMonahan** [comment]
I presume that the build is using clang, so I guess it is using this version:
```
% clang --version
Apple clang version 11.0.0 (clang-1100.0.33.16)
Target: x86_64-apple-darwin23.1.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

Background information: I'm only here because I tried to install the Shopify Ruby-LSP extension for Visual Studio Code, for a Ruby project that is on an old version of Ruby, so I followed the instructions at https://github.com/Shopify/vscode-ruby-lsp?tab=readme-ov-file#ruby-version-requirement to install a recent Ruby via ruby-install and chruby, and a Custom Gem in the .vscode folder.  After battling Homebrew and OpenSSL to get Ruby 3.2.2 installed, I got the compilation error in the prism gem.  The Gemfile for Shopify-LSP is supposed to look like this:
```
# frozen_string_literal: true
source "https://rubygems.org"
gem "ruby-lsp"
gem "rubocop"
```
but I ended up adding the following to get it working:
```
gem "prism", "= 0.16.0"
```

Thus I have no need to resolve this problem myself, but I thought it might be useful information.

**Comment by kddnewton** [comment]
Yeah I'm just going to disable that warning. `{ 0 }` is definitely C99 standard. See https://www.open-std.org/jtc1/sc22/wg14/www/docs/n1256.pdf section 6.7.8.21. I'll leave this issue open and track it for disabling.

**Comment by enebo** [comment]
> Another way is just adding `-Wno-missing-braces` to the Makefile, if this seems buggy behavior and `{ 0 }` is supposed to be C99 standard (which https://lore.kernel.org/git/xmqq7d4kp8l6.fsf@gitster.g/t/ seems to claim, but not sure it's true). I think memset() is a nicer and clearer solution (IMO it's weird syntax to write one zero and expect to init all fields, should be either `{}` then or explicitly init all).

I recall that memset() was rejected earlier because of a possible performance cost.  I had wondered if it makes sense to make a ```#define``` for initializations based on what they are then you would have something like:

```C
#define  PM_OPTIONS_T_INIT { { 0 }, 0, { 0 }, 0, 0, 0, 0 }

pm_options_t options = PM_OPTIONS_T_INIT; 
```

All types could just be inited using vocabulary which matches the type and only one place needs to be changed if the struct changes.

**Comment by froydnj** [comment]
Alternatively, maybe the `Makefile` shouldn't unconditionally enable `-Werror` for releases, but only have it in place for development?  One can't control what compilers people are using in the wild.

**Comment by kddnewton** [comment]
We previously had macros for everything like that and it became very annoying to maintain, and then one slipped into the CRuby codebase, which is what got me on the kick to remove them all. `= { 0 }` works just fine and is in the standard, I'd prefer to use it and just remove the warning. Not to mention the fact that it's nice that when new fields are added to structs, nothing has to change about the initialization code.

We could consider not enabling `-Werror`, but this is really the only warning that has consistently given us trouble, so I think it's probably okay for now. If we hit this kind of thing again I'd consider it more.

**Comment by eregon** [comment]
@JonathanMonahan FWIW it seems `Apple clang version 11.0.0` is from XCode 11 which itself came out on macOS Mojave.
So basically it sounds like you have a very old XCode installed on the latest macOS version, so it's probably best to update your XCode to latest or so to avoid such compilation issues/troubles (unless you are using an old XCode on purpose of course).

@kddnewton Thanks for the reference to the standard, `-Wno-missing-braces` seems a good fix then.

**Comment by JonathanMonahan** [comment]
@eregon Thank you - I'm a developer on a Mac, not a Mac developer!

In case anyone else is interested, I found an appropriate StackOverflow article, ran `sudo xcode-select -r` and now I have a more up-to-date `clang`:
```
jonathan@Jonathans-MacBook-Pro-2 ~ % where clang         
/usr/bin/clang
jonathan@Jonathans-MacBook-Pro-2 ~ % xcode-select -p
/Library/Developer/CommandLineTools
jonathan@Jonathans-MacBook-Pro-2 ~ % sudo xcode-select -r
Password:
jonathan@Jonathans-MacBook-Pro-2 ~ % where clang         
/usr/bin/clang
jonathan@Jonathans-MacBook-Pro-2 ~ % xcode-select -p     
/Applications/Xcode.app/Contents/Developer
jonathan@Jonathans-MacBook-Pro-2 ~ % clang --version
Apple clang version 15.0.0 (clang-1500.0.40.1)
Target: x86_64-apple-darwin23.1.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by JonathanMonahan** [comment]
...and that appears to have solved the problem.  I commented out the `Gemfile` line that pegged the `prism` gem to version 0.16.0, and ran `bundle update`:
```
jonathan@Jonathans-MacBook-Pro-2 VSCode % bundle update 
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Fetching prism 0.17.1
Fetching sorbet-runtime 0.5.11128 (was 0.5.11122)
Installing sorbet-runtime 0.5.11128 (was 0.5.11122)
Installing prism 0.17.1 with native extensions
Fetching ruby-lsp 0.12.3 (was 0.11.2)
Installing ruby-lsp 0.12.3 (was 0.11.2)
Bundle updated!
jonathan@Jonathans-MacBook-Pro-2 VSCode % 
```
