### ISSUE TITLE
[COMPILER] Missing `defined?` for CallNodes

### ISSUE THREAD

**Issue by jemmaissroff** [ruby/prism#1888]
`defined?(a.b)` (defined on a CallNode)

Example file: `RUBY_ISEQ_DUMP_DEBUG=prism make test-all TESTS=test/-ext-/bug_reporter/test_bug_reporter.rb`

**Comment by tenderlove** [comment]
I merged https://github.com/ruby/ruby/pull/9089 so I think we can close this.

**Comment by tenderlove** [comment]
Also `RUBY_ISEQ_DUMP_DEBUG=prism make test-all TESTS=test/-ext-/bug_reporter/test_bug_reporter.rb` passes
