### ISSUE TITLE
Inconsistent naming: CallNode#message_loc and CallNode#name

### ISSUE THREAD

**Issue by eregon** [ruby/prism#1893]
Since they are about the same thing, it seems best to rename CallNode#message_loc to CallNode#name_loc.
And the same for CallOrWriteNode, CallOperatorWriteNode, CallAndWriteNode (which have message_loc, read_name, write_name).

**Comment by kddnewton** [comment]
This one is on purpose. Because you can have aref, `message_loc` might point to `[foo, bar, baz]`. In this case I don't want consumers to think that `name_loc` is going to be the same thing as `name`, because `name` can be synthesized.

**Comment by eregon** [comment]
I see, it'd be nice to document this/explain this example, probably in the comment for CallNode.
