### ISSUE TITLE
Could DefNode#parameters be never nil/null?

### ISSUE THREAD

**Issue by eregon** [ruby/prism#1915]
Currently it's null for this case:
```
$ bin/parse -e 'def m; end'
@ ProgramNode (location: (1,0)-(1,10))
├── locals: []
└── statements:
    @ StatementsNode (location: (1,0)-(1,10))
    └── body: (length: 1)
        └── @ DefNode (location: (1,0)-(1,10))
            ├── name: :m
            ├── name_loc: (1,4)-(1,5) = "m"
            ├── receiver: ∅
            ├── parameters: ∅
            ├── body: ∅
            ├── locals: []
            ├── def_keyword_loc: (1,0)-(1,3) = "def"
            ├── operator_loc: ∅
            ├── lparen_loc: ∅
            ├── rparen_loc: ∅
            ├── equal_loc: ∅
            └── end_keyword_loc: (1,7)-(1,10) = "end"
```

But it could just be a ParametersNode with everything empty, and then be a non-optional field.
This leads to every use of a DefNode to have to consider it being nil/null and e.g. if it wants to know the number of required arguments then have this extra check.

I'm working around by creating it empty manually in TruffleRuby.

**Comment by enebo** [comment]
@eregon this will increase the serialized size by creating a node just to have no contents in it.  I hot path this case to just be an arity check without going through all the other machinery of seeing how to bind stuff.  This is a rare case where I prefer a null field.

**Comment by eregon** [comment]
@enebo Yeah I could see that.
OTOH it seems nicer to always have the node for e.g. Ruby users of the gem.

FWIW I'm using this in Java:
```java
public static final Nodes.ParametersNode ZERO_PARAMETERS_NODE = new Nodes.ParametersNode(EMPTY_NODE_ARRAY,
            EMPTY_NODE_ARRAY, null, EMPTY_NODE_ARRAY, EMPTY_NODE_ARRAY, null, null, 0, 0);
...
        var parametersNode = environment.parametersNode;
        if (parametersNode == null) {
            // parametersNode == null for a method means zero parameters: https://github.com/ruby/prism/issues/1915
            parametersNode = ZERO_PARAMETERS_NODE;
        }
```

**Comment by enebo** [comment]
@eregon serialize+load and gem side of things do not need to behave the same way here.  config.yml says it can be null but ruby templates could do effectively what you are (construct an empty node).

For that matter since we both can stuff things via our Java engine env you could just make this zero param node in Loader for TR only.

**Comment by enebo** [comment]
For posterity this is how my null check looks:

```java
        if (parameters == null) {
            addInstr(new CheckArityInstr(0, 0, false, -1, UndefinedValue.UNDEFINED));
            return;
        }
```

your mileage may vary but no-args is very common and this is just walking through a lot less logic.

**Comment by haldun** [comment]
AFAIK this was intentional https://github.com/ruby/prism/pull/962

**Comment by eregon** [comment]
> your mileage may vary but no-args is very common

I was thinking it's not that common.
I wrote a small script to count that, for truffleruby's core library:
```ruby
require 'prism'

files = Dir['src/main/ruby/truffleruby/core/**/*.rb']

def_nodes = 0
def_nodes_no_parameters = 0

visitor = Class.new(Prism::Visitor) do
  define_method(:visit_def_node) do |node|
    def_nodes += 1
    def_nodes_no_parameters += 1 unless node.parameters
    super(node)
  end
end.new

files.each { |file|
  puts file
  parse_result = Prism.parse_file(file)
  parse_result.value.accept(visitor)
}

p [def_nodes_no_parameters, def_nodes]
puts '%.2f' % (def_nodes_no_parameters / def_nodes.to_f)
```
```
[663, 2416]
0.27
```
So 27% of methods do not have parameters, that's much more than I thought.
It's even 71% for Rails `rails/**/*.rb` and 37% for `rails/*/lib/**/*.rb`!

So yeah given how frequent it is this optimization is likely worth it.

We could make it nicer for Prism users though and automatically return a constant empty ParametersNode, or similar.
Maybe just the `Prism:: ParametersNode::ZERO_PARAMETERS_NODE` constant would be helpful, so it could be used like:
```ruby
def visit_def_node(node)
  params = node.parameters || Prism:: ParametersNode::ZERO_PARAMETERS_NODE
  ...
end
```

**Comment by kddnewton** [comment]
As already stated, I definitely don't want to allocate all of that memory for nothing, and I also don't want to put it into the serialization for nothing. At the moment all of the consumers expect that a `node?` can be `nil`/`NULL`, so I don't want to change that for just a single node. If we want to introduce a `node?+default` or something in the future, we can consider that, but I wouldn't only do that for this one place, we would want to do that for the whole tree where it would make sense (like empty statements nodes and others). Going to close this one.
