### ISSUE TITLE
[Documentation] A short table providing an overview between Prism and Ripper

### ISSUE THREAD

**Issue by rubyFeedback** [ruby/prism#1918]
Hi,

Recently I read:

https://www.ruby-lang.org/en/news/2023/11/12/ruby-3-3-0-preview3-released/

"Prism is production ready and actively maintained, you can use it in place of Ripper"

Would it be possible to add a table somewhere, be it on the main README, or
the wiki, and provide a link to this table, that **briefly mentions relevant stats
and differences, advantages and disadvantages between prism and Ripper**?

I don't mean this necessarily as an advertisement for prism, but simply what
a semi-experienced developer may experience what the core differences may
be, e. g. when to use prism or ripper, and why. The table does not need to
mention everything, mind you - I am looking for a simple overview, on a
first glance, and if then AFTERWARDS more questions may arise, then we can
add links to the relevant subsections there. But the important first step would
be to provide a quick insta-look overview between ripper and prism, so people
can understand the differences better. Right now I don't really know the differences;
I know a bit of ripper, but nothing about prism yet, so any initial points may be
helpful. At any rate thank you for reading this request.

**Comment by kddnewton** [comment]
Hi @rubyFeedback - yeah I'm happy to provide a table. We're a little booked up until the 3.3 release, but I can make this a priority after. Thanks for the report.

**Comment by kddnewton** [comment]
This is now on `main` in https://github.com/ruby/prism/blob/main/docs/ripper_translation.md
