### ISSUE TITLE
[COMPILER] Investigate and implement tracepoints in prism compilation

### ISSUE THREAD

**Issue by jemmaissroff** [ruby/prism#1940]
This is lower priority than the other compiler issues, as we _could_ release 3.3 without this working fully.

We currently do not support all tracepoint behavior on prism compilation in CRuby. We should support it. Investigate what is missing, and the outcome of this ticket should either be other tickets to track the work on tracepoints, or completed tracepoint behavior.

**Comment by kddnewton** [comment]
This is now covered by individual tracepoint issues, so I'm going to close this meta-issue.
