### ISSUE TITLE
Experience trying to find Prism.lex options

### ISSUE THREAD

**Issue by schneems** [ruby/prism#1969]
I like to document difficulties I have when starting out, otherwise the curse of knowledge makes it hard for me to remember later. Let me know if you want me to keep these observations to myself or put them somewhere else (such as a slack thread).

Fair warning: this is going to be a bit stream-of-concious. I'm writing as I'm looking. 

## Issue

I'm trying to translate this ripper code into a prism API:

```
          Ripper::Lexer.new(lines.join, "-", lineno + 1).parse.sort_by(&:pos)
```

I'm looking at https://github.com/ruby/prism/blob/35e82ce038dc0b727f2f61e8ec3c9badd5070e9c/docs/ruby_api.md. I see there's a `Prism.lex` which is a C method (not sure where it lives, but didn't spend much time poking). I found Prism.lex_compat in the source code. Looking for that source I'm reminded of the ripper.md docs which doesn't mention options. I found https://github.com/ruby/prism/blob/35e82ce038dc0b727f2f61e8ec3c9badd5070e9c/lib/prism.rb#L45 which mentions options are the same as `Prism.parse` which I'm not entirely sure where to find those docs. I'm hoping maybe the generated docs will link it.

Now I'm at https://rubydoc.info/gems/prism for 0.18.0. It's not linked in https://rubydoc.info/gems/prism/Prism.lex_compat but I was able to manually find it https://rubydoc.info/gems/prism/Prism.parse and it has the options that I want. 

## Retro 

I was able to find what I need, but there's some opportunities (possibly) worth calling out:

- The `Prism.parse` mention could generate a link.
- The Ruby API docs could list the options or link to somewhere that does.

Again, not really a major problem, but I'm still exploring. I'm not sure what level of fidelity or feedback is useful to the project. It's 100% okay to close this issue.

**Comment by kddnewton** [comment]
I'm not quite certain how rubydoc.info works, but it looks like it's not doing the linking that our documentation website does. For example:

https://ruby.github.io/prism/rb/Prism.html#method-c-lex

I think maybe YARD and rdoc have different conventions, but we're sticking with rdoc conventions because that's what the rest of CRuby core stuff does. So unfortunately this might be out of scope.
