### ISSUE TITLE
Docs for lex_compat say result is an Array when actual result is ParseResult

### ISSUE THREAD

**Issue by schneems** [ruby/prism#1971]
These docs https://github.com/ruby/prism/blob/962e1e7adc039077349f640cefb17de20b7b4867/lib/prism.rb#L39 tell me that. this call returns an Array (presumably similar to the Ripper output). 

```
  #   Prism::lex_compat(source, **options) -> Array
```

However, I'm seeing:

```
$ gem install prism
Building native extensions. This could take a while...
Successfully installed prism-0.18.0
Parsing documentation for prism-0.18.0
Installing ri documentation for prism-0.18.0
Done installing documentation for prism after 1 seconds
1 gem installed
⛄️ 3.1.4 🚀 /Users/rschneeman/Documents/projects/syntax_suggest (schneems/prism-numero-uno)
$ irb
irb(main):001:0> require 'prism'
=> true
irb(main):002:0> Prism.lex_compat("def foo(value); print value; end", line: 1).class
=> Prism::ParseResult
```

I'm not sure if this was intentional or accidental (i.e. are the docs wrong or is the return wrong). Otherwise, I would have sent a PR if I knew the docs were wrong.

For context: The 0.18.0 release was on November 22, and this line was last updated on November 3rd in this PR https://github.com/ruby/prism/pull/1763

**Comment by schneems** [comment]
Calling `.values` on the ParseResult seems to give me the output that I'm after. 

Though it returns an array of arrays where Ripper returns an array of structs. The array access meets my needs and is probably how most people use the lex output anyway, just noting that it was a surprise/difference.

**Comment by eregon** [comment]
Yeah the docs are wrong, they need to be updated.
And it's `.value` not `.values` (in your comment above)

**Comment by kddnewton** [comment]
Updated the docs to fix this!
