### ISSUE TITLE
[COMPILER] Broken break

### ISSUE THREAD

**Issue by jemmaissroff** [ruby/prism#1986]
Minimal repro:

```
[true].map do
  break
end
```

A test that is currently failing that should pass upon successful completion of this issue:

RUBY_ISEQ_DUMP_DEBUG=prism make test/did_you_mean/edit_distance/test_jaro_winkler.rb

**Comment by jemmaissroff** [comment]
`RUBY_ISEQ_DUMP_DEBUG=prism make test/cgi/test_cgi_session.rb` is an example of another test that I think is affected

**Comment by paracycle** [comment]
In case it is helpful, the specific failure in `test_cgi_session.rb` is this call:
```ruby
%w[SHA512 SHA384 SHA256 SHA1 RMD160 MD5].each do |algo|
    begin
      break Digest(algo)
    rescue LoadError
    end
  end
```
which is supposed to return the first matching `Digest` instance, but returns an array with Prism compiler, instead.
