### ISSUE TITLE
Hash literals should warn on duplicated keys

### ISSUE THREAD

**Issue by kddnewton** [ruby/prism#2005]
```ruby
{ a: 1, a: 1 }
```

**Comment by enebo** [comment]
The specific warning should be:  `-e:1: warning: key :a is duplicated and overwritten on line 1`

**Comment by andrykonchin** [comment]
One more case:

```ruby
{a: 1, **{a: 2}}
```

**Comment by kddnewton** [comment]
Done on `main`

**Comment by kddnewton** [comment]
Ahh sorry, I have a branch for it and thought I had merged it
