### ISSUE TITLE
[COMPILER] Broken MultiWriteNode with index access

### ISSUE THREAD

**Issue by jemmaissroff** [ruby/prism#2017]
There might be a more minimal repro, but some version of this is broken:

`_, {}[:a] = 1`

Found from this test: `RUBY_ISEQ_DUMP_DEBUG=prism make test/fiber/test_storage.rb`

**Comment by eightbitraptor** [comment]
@jemmaissroff This is giving me

```
./test.rb:10:in `compile_prism': node type PM_INDEX_TARGET_NODE not implemented (NotImplementedError)
```

Is that what you expected to see?

**Comment by jemmaissroff** [comment]
Confusingly, yes! I created the bug before we implemented `IndexTargetNode` and `CallTargetNode` on the prism side. The bug was due to them not existing, and us not implementing their compilation (in their absence) correctly.

Now that they exist, the way the bug manifests changes, but it's still the same root bug. Does that make sense?
