### ISSUE TITLE
InterpolatedStringNode and InterpolatedXStringNode can be frozen

### ISSUE THREAD

**Issue by tompng** [ruby/prism#2036]
Some string without embed have several parts and represented by InterpolatedStringNode.
These string is frozen if there is frozen_string_literal magic comment.

```ruby
# frozen_string_literal: true
frozen_string = %[a] "b" 'c'
p frozen_string.frozen? #=> true
```

```ruby
# frozen_string_literal: true
<<A; frozen_string = 'aaa
A
aaa'
p frozen_string.frozen? #=> true
```

InterpolatedXStringNode without embed is also frozen.
```ruby
def (o=Object.new).`(s)=p(s.frozen?)
<<A; o.instance_eval { `aaa
A
aaa` }
#=> true
```

**Comment by kddnewton** [comment]
Yes, we'll get this fixed, thanks!

**Comment by kddnewton** [comment]
There is now a flag for this for the interpolated string. For the interpolated x string, it's assumed that they're always frozen.
