### ISSUE TITLE
:type field for deconstruct_keys

### ISSUE THREAD

**Issue by tompng** [ruby/prism#2044]
I think adding `type:` to deconstruct_keys is useful.
```ruby
node in { type: :foobar_node, foo:, bar: }
```

Using Visitor and pattern matching, it is easy to find a code pattern from AST.
If `deconstruct_keys` respond to `:type` field, it will be more easy for pattern matching to child nodes.
```ruby
def visit_local_variable_write_node(node)
  super
  if node in { name:, value: { type: :call_node, name: :rand } } # Can't do this now
    puts "assign rand to lvar #{name}"
  end
  if node in { name:, value: { receiver:, arguments:, name: :rand } } # Workaround
  end
end
```

I was writing a code like this https://gist.github.com/tompng/a065d8cf2475c9b6bde5cc6801b3e846

**Comment by kddnewton** [comment]
Does matching against the constant suit your needs? As in:

```ruby
def visit_local_variable_write_node(node)
  super
  if node in { name:, value: CallNode[name: :rand] } # Can't do this now
    puts "assign rand to lvar #{name}"
  end
end
```

**Comment by tompng** [comment]
Yes, that's what I wanted. I didn't know that syntax, thank you.

**Comment by kddnewton** [comment]
No problem!
