### ISSUE TITLE
Should Hash key nodes be marked frozen?

### ISSUE THREAD

**Issue by enebo** [ruby/prism#2045]
Hash keys are frozen so we can look things up later:

```ruby
h = {"a" => 1}
p h.keys.first.frozen?
```

In legacy parsers we mark String keys as frozen and do not require it be done later.  With how hashes are constructed you could argue this is not needed but this has a couple of benefits:

  1. builders will immediately know this is frozen and dedup the string (this could still be done in the builder -- I am adding this logic explicitly in JRuby in prism builder)
  2. syntax tools should be able to tell this is a frozen value (tools could figure this out as well but it would be more icky)

So this is something that can be figured out without C parser marking it for us but it would simplify consumers code if it was marked like the current parsers.

**Comment by kddnewton** [comment]
Yeah that's a good point, we should do this.

**Comment by kddnewton** [comment]
Fixed on `main`
