### ISSUE TITLE
[COMPILER] Seg fault with locals within blocks within rescues

### ISSUE THREAD

**Issue by jemmaissroff** [ruby/prism#2053]
```
begin
rescue
  a = 1
  b = 2
  [].each { a = 2 }
end
```

I don't know that this is 100% minimal as a repro, there could be a way to simplify it

Found here: `RUBY_ISEQ_DUMP_DEBUG=prism make test/io/console/test_io_console.rb`

**Comment by eightbitraptor** [comment]
https://github.com/ruby/ruby/pull/9445
