### ISSUE TITLE
Should InterpolatedMatchLastLineNode/MatchLastLineNode just wrap a regexp node?

### ISSUE THREAD

**Issue by eregon** [ruby/prism#2057]
I.e. instead of having InterpolatedMatchLastLineNode and MatchLastLineNode,
having a MatchLastLineNode wrapping a RegularExpressionNode or InterpolatedRegularExpressionNode.

In terms of compilation both InterpolatedMatchLastLineNode/MatchLastLineNode seem handled the same way, recreate the (currently missing) regexp node and then create a call for `regexp =~ $_` on it.

Not very important, but it seems a case of having an extra node type for little benefit.

**Comment by kddnewton** [comment]
This one requires less memory and doesn't require you to descend down into the child node, so I'd rather keep it this way for now.
