### ISSUE TITLE
Adding kind for node[] fields where possible

### ISSUE THREAD

**Issue by eregon** [ruby/prism#2058]
For at least some of the node[] we could give a kind and so that array's elements would have a proper type in documentation, Java code, etc.
Some example:
* MatchWriteNode#targets, (I think) always LocalVariableTargetNode

Some counter example:
* ParametersNode#requireds, not always RequiredParameterNode, can also be MultiTargetNode

In some cases it's not possible because multiple classes are possible, or a MissingNode is possible.

**Comment by kddnewton** [comment]
Yes I agree. I think we should also use this opportunity to expand the syntax to support a set of nodes for languages where a union makes sense.

**Comment by eregon** [comment]
Indeed, a union would be super helpful, even if it only ends up in documentation.
(Java doesn't have union types unfortunately)

**Comment by eregon** [comment]
Probably we can consider this done when https://github.com/ruby/prism/pull/2101#discussion_r1445812790 is merged.
