### ISSUE TITLE
Add visibility flag for CallNode

### ISSUE THREAD

**Issue by eregon** [ruby/prism#2060]
It would be very helpful for compiling CallNode (and for other semantic usages of Prism) to know if a call should consider visibility or ignore visibility.
Something like `boolean ignoreVisibility = node.receiver == null || node.receiver instanceof SelfNode` is not correct for complex cases like `self.foo &&= 42` when it's desugared to `a=self; a.foo && a.foo = 42` as then the `foo=` call would check visibility but it should not.
The easiest solution for this is to have a visibility flag on CallNode.

**Comment by enebo** [comment]
@eregon you want this flag specifically because you desugar nodes to callnodes and no longer know if you should perform a visibility check or not?  Or is there some other place where this is useful?   If not you could just desugar to your own call type which extends CallNode which contains this flag.  We also have engine-specific flags so you could possibly add this at that point too.

**Comment by eregon** [comment]
It's mainly useful when desugaring, indeed. It's also nicer than checking `node.receiver == null || node.receiver instanceof SelfNode` but that's a smaller deal.
One cannot `extends CallNode` because it's a `final class` and it should remain so for best performance.
I could try to define my own flag and steal one bit but that's incredibly brittle and hacky of course.

I think visibility is a useful high-level property of a call node, valuable for many usages of Prism, similar to attribute assign, safe navigation and vcall. And it seems the best to keep this information when desugaring.

**Comment by enebo** [comment]
@eregon fwiw since there is already flags on CallNode it won't take up more space so I don't think this hurts to add.

**Comment by eregon** [comment]
Yeah, exactly, it's free memory-wise.

**Comment by kddnewton** [comment]
So would this only be on `CallNode`? And it would set it if its missing a receiver or if the receiver is `self`?

**Comment by eregon** [comment]
I think it'd make sense to add for all `Call*Node`, so CallNode, CallAndWriteNode, CallOrWriteNode, CallOperatorWriteNode, CallTargetNode.
They all already have flags (of type CallNodeFlags) so it's free in footprint to add it, and it seems best to always have it.

> And it would set it if its missing a receiver or if the receiver is `self`?

Correct. It's easy to check during parsing, but much more messy to carry this information around later if it's not saved during parsing.

**Comment by kddnewton** [comment]
I guess I'm not sure what the visibility would be for the Call*Node nodes, would it be the same calculation? We would just forward on the flag?

**Comment by eregon** [comment]
Yes, it's the same condition, whether the receiver is `self` or no receiver.

Exactly, when desugaring (e.g. in TruffleRuby) we'd forward that flag e.g. from `CallOperatorWriteNode` to `CallNode`.

**Comment by eregon** [comment]
Ah it's also `Index*Node` since those are also calls.
IOW for all nodes using `CallNodeFlags`.

**Comment by kddnewton** [comment]
Okay, I think we can make this happen.
