### ISSUE TITLE
[COMPILER] Incorrect iseqs for ClassVariableOrWriteNodes

### ISSUE THREAD

**Issue by jemmaissroff** [ruby/prism#2064]
Minimal repro with wrong iseqs:

`@@foo ||= 1`

I can't get it to crash in the minimal repro, but the test this comes from is `RUBY_ISEQ_DUMP_DEBUG=prism make test/csv/interface/test_read_write.rb`

**Comment by eileencodes** [comment]
This is fixed by https://github.com/ruby/ruby/pull/9237
