### ISSUE TITLE
Heredocs not properly escaping with backslash followed by newline

### ISSUE THREAD

**Issue by enebo** [ruby/prism#2074]
```ruby
puts <<~HERE
      a
      b\
      c
    HERE
```

This should be:

```text
a
bc
```

but is:
 
```text
a
b      c
```

So it appears to remove the `\n` but then doesn't eat the extra whitespace on the next line.

**Comment by kddnewton** [comment]
... what. I had no idea it was supposed to eat the extra whitespace. That's... so weird. I will get this fixed, but probably not by 3.3.

**Comment by enebo** [comment]
@kddnewton heredocs is a scary place.  the dedent feature is extra scary.

**Comment by rwstauner** [comment]
I was curious so I looked into this only to realize that it needs to eat the leading whitespace that matches the ultimately common whitespace which might be decided after this line (which seems substantially more complicated):

```
$ cat heredoc.rb
def main
  puts <<~HERE.inspect
    a
    b\
    c
   d
  HERE
end
main
$ ruby -v heredoc.rb
ruby 3.4.0dev (2024-01-18T15:35:46Z master 00814fd672) [arm64-darwin23]
" a\n b c\nd\n"
$ ruby --parser=prism heredoc.rb
" a\n b    c\nd\n"
```

**Comment by kddnewton** [comment]
That's okay that's already what we do anyway.
