### ISSUE TITLE
yield in proc in invalid context should SyntaxError

### ISSUE THREAD

**Issue by enebo** [ruby/prism#2075]
```ruby
1.times { yield }
```

This should raise:

```text
-e:1: Invalid yield (SyntaxError)
```

**Comment by kddnewton** [comment]
Ahh yeah that one is covered by https://github.com/ruby/prism/issues/1604. Also very high on the list!

**Comment by enebo** [comment]
@andrykonchin not sure how easy this is in TR but when I build yield I have some logic like:

```java
+        IRScope hardScope = scope.getNearestNonClosurelikeScope();
+        if (hardScope instanceof IRScriptBody || hardScope instanceof IRModuleBody) throwSyntaxError(getLine(node), "Invalid yield");
```

This won't be needed when #1604 is fixed but it wasn't too hard a workaround.
