### ISSUE TITLE
END within method should warn (when using serialization API)

### ISSUE THREAD

**Issue by enebo** [ruby/prism#2080]
If I run this snippet through parse I see the warning:

```ruby
def foo; END {}; end
```

```text
Warnings:
[#<Prism::ParseWarning @message="END in method; use at_exit" @location=#<Prism::Location @start_offset=9 @length=3 start_line=1>>]

AST:
@ ProgramNode (location: (1,0)-(1,20))
├── locals: []
└── statements:
    @ StatementsNode (location: (1,0)-(1,20))
    └── body: (length: 1)
        └── @ DefNode (location: (1,0)-(1,20))
            ├── name: :foo
            ├── name_loc: (1,4)-(1,7) = "foo"
            ├── receiver: ∅
            ├── parameters: ∅
            ├── body:
            │   @ StatementsNode (location: (1,9)-(1,15))
            │   └── body: (length: 1)
            │       └── @ PostExecutionNode (location: (1,9)-(1,15))
            │           ├── statements: ∅
            │           ├── keyword_loc: (1,9)-(1,12) = "END"
            │           ├── opening_loc: (1,13)-(1,14) = "{"
            │           └── closing_loc: (1,14)-(1,15) = "}"
            ├── locals: []
            ├── locals_body_index: 0
            ├── def_keyword_loc: (1,0)-(1,3) = "def"
            ├── operator_loc: ∅
            ├── lparen_loc: ∅
            ├── rparen_loc: ∅
            ├── equal_loc: ∅
            └── end_keyword_loc: (1,17)-(1,20) = "end"
```

Loader is seeing 0 warnings so this is not making it into the serialized blob.

**Comment by kddnewton** [comment]
```ruby
"def foo; END {}; end".then { |source| Prism.load(source, Prism.dump(source)) }
```

With this code I'm seeing the warning. Any chance you're setting `verbose` to `nil`?

**Comment by enebo** [comment]
Perhaps the issue is not all warnings only emit is verbose is true.  This I think is one of those?

**Comment by kddnewton** [comment]
Oh no really? I thought everything checked verbose. I'll see what I can find out.

**Comment by enebo** [comment]
I just checked with `-vw` and I also do not see this so I think I probably am not passing verbose in either.

**Comment by kddnewton** [comment]
I'm not sure what's going on here exactly. If you set `VERBOSE=nil` this warning does not appear, if you set `VERBOSE=false` it does appear. For all of the other warnings I checked, `VERBOSE=false` also makes them appear.

**Comment by kddnewton** [comment]
I think this is indicative that we need to create a centralized Java class to serialize the options going into the JNI/JNR call.

**Comment by enebo** [comment]
```text
ruby -e 'p $VERBOSE; def foo; END {}; end'
-e:1: warning: END in method; use at_exit
false
```

This is 3.2.2 with no options.

**Comment by kddnewton** [comment]
Right, that makes sense. There's a difference between `VERBOSE=nil` and `VERBOSE=false` unfortunately.

**Comment by kddnewton** [comment]
I think in our case, you should pass indicate that it's verbose if `$VERBOSE != nil`

**Comment by enebo** [comment]
The Java I use is:

```java
metadata.append(runtime.getInstanceConfig().getVerbosity() == RubyInstanceConfig.Verbosity.NIL ? 0 : 1);
```

So I already do that and confirm it is 1 so unless it is in wrong place I don't know.

**Comment by enebo** [comment]
oh I think I reversed this value!  supress warnings.

**Comment by enebo** [comment]
LOL.  I was marking as warnings and not supress warnings.  I think this is my brain just assuming all values are positive assertions and not negative.  It is something I religiously do so I probably just spaced this out.  Sorry for the confusion.

**Comment by eregon** [comment]
Actually that part of the API will likely need to change or have an extra flag, because there are 3 states for `$VERBOSE` and some parser warnings warn at `false` while some only warn at `true` (and of course none warn at `nil`):
```
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]
$ ruby -e 'def foo; END {}; end' 
-e:1: warning: END in method; use at_exit
$ ruby -e '(1; 2)'            
$ ruby -w -e '(1; 2)'
-e:1: warning: unused literal ignored
-e:1: warning: possibly useless use of a literal in void context
```

I was thinking about this with @andrykonchin the other day, but didn't find an example, but now there is one.
I'll file a separate issue to avoid mixing things.
