### ISSUE TITLE
Missing `EncodingError` for Symbol literal with invalid encoding

### ISSUE THREAD

**Issue by andrykonchin** [ruby/prism#2129]
Looks like CRuby checks this at parsing time:

```
ruby -c -e ':"\xC3"'
ruby: invalid symbol in encoding UTF-8 :"\xC3" (EncodingError)
```

**Comment by eregon** [comment]
This also caused some IRB tests to fail: https://github.com/ruby/irb/pull/854
Also some occurrences in ruby/spec and test-all mentioned by @enebo in #2472.

**Comment by enebo** [comment]
@eregon @andrykonchin Of course it would be nice if this is fixed but it is worked around pretty easily by just doing a CR scan and look for broken.  Then you can remove those omit's and when it is fixed only delete something from your own source.

**Comment by kddnewton** [comment]
This should be fixed on `main`.
