### ISSUE TITLE
Location of DATA seems incorrect

### ISSUE THREAD

**Issue by andrykonchin** [ruby/prism#2142]
In the following example:

```
cat script.rb
1 + 2
__END__
123
```

Location of DATA is `#<Prism::Location @start_offset=6 @length=12 start_line=2>` what is supposed to point at a position in the file where DATA is starting, that's a position after `__END__`. The index of a byte after `__END__` is ~14.

I suppose the location points at a position after `__END__` because of the following comment:
```
# lib/prism/parse_result.rb

    # An optional location that represents the location of the content after the
    # __END__ marker. This content is loaded into the DATA constant when the
    # file being parsed is the main file being executed.
    attr_reader :data_loc
```

On the other hand in the `docs/serialization.md` document location is described as `the optional location of the __END__ keyword and its contents` what contradicts with the comment above.

Could you please clarify how to interpret correctly provided location?

I may assume the location can point at the last position **before** `__END__` and we need just to add length of `__END__` + 1 for the following "\n". Is it correct?

```
bin/parse script.rb
DATA:
#<Prism::Location @start_offset=6 @length=12 start_line=2>

AST:
@ ProgramNode (location: (1,0)-(1,5))
├── locals: []
└── statements:
    @ StatementsNode (location: (1,0)-(1,5))
    └── body: (length: 1)
        └── @ CallNode (location: (1,0)-(1,5))
            ├── flags: ∅
            ├── receiver:
            │   @ IntegerNode (location: (1,0)-(1,1))
            │   └── flags: decimal
            ├── call_operator_loc: ∅
            ├── name: :+
            ├── message_loc: (1,2)-(1,3) = "+"
            ├── opening_loc: ∅
            ├── arguments:
            │   @ ArgumentsNode (location: (1,4)-(1,5))
            │   ├── flags: ∅
            │   └── arguments: (length: 1)
            │       └── @ IntegerNode (location: (1,4)-(1,5))
            │           └── flags: decimal
            ├── closing_loc: ∅
            └── block: ∅
```

**Comment by kddnewton** [comment]
I just pushed a commit to clarify the comments. The location is always going to point to the start of the `__END__` marker. To get to the contents, it will be:

```ruby
offset = result.data_loc.start_offset + "__END__".length
source[offset] == "\r" ? offset + 2 : offset + 1
```

Assuming `result` is a `Prism::ParseResult` and `source` is a string containing the source. We need to check for `\r\n` which is why the ternary exists.

**Comment by andrykonchin** [comment]
Thank you!
