### ISSUE TITLE
eval encoding with magic comment still not correct

### ISSUE THREAD

**Issue by enebo** [ruby/prism#2145]
This is something not quite right even after #1639:

```ruby
code = "# encoding: UTF-8\na = 'é'; puts a; a.encoding".b
p code.encoding
p eval(code)
```
This prints out:

```text
#<Encoding:ASCII-8BIT>
é
#<Encoding:ASCII-8BIT>
```

**Comment by enebo** [comment]
Looking in debugger it appears like perhaps encoding from Loader is getting set to ASCII-8BIT and not pragma encoding?

**Comment by eregon** [comment]
And it also works fine with Prism.parse on TruffleRuby (using FFI):
```
$ ruby -Ilib -rprism -e 'r = Prism.parse "# encoding: iso-8859-1\na = %{é}; puts a; a.encoding", encoding: Encoding::BINARY; p r.source.source.encoding'
#<Encoding:ISO-8859-1>
$ ruby -Ilib -rprism -e 'r = Prism.parse "a = %{é}; puts a; a.encoding", encoding: Encoding::BINARY; p r.source.source.encoding'           
#<Encoding:ASCII-8BIT>
```

Although `encoding: "BINARY"` doesn't work for the FFI backend, it needs `encoding: Encoding::BINARY`, probably we should fix that.

So not quite sure where is the bug, but it doesn't seem to be in Prism C code because serialization gets it right too.
Another way to show it:
```
$ ruby -Ilib -rprism -e 'p Prism.dump "# encoding: iso-8859-1\na = %{é}; puts a; a.encoding", encoding: Encoding::BINARY'
"PRISM\x00\x13\x00\x00\nISO-8859-1\x02\x01\x00\x00\x16\x01\x02\b\f\n\x00\x00\x00r\x00\x00\x00\x03w\x17\x1D\x01\x01\x89\x17\x1D\x03`\x17\t\x01\x00\x17\x01\x8A\e\x05\x00\x01\e\x02\x1D\x02\x01\x1F\x01\x01\x1D\x02\x19\x01\x13\"\x06\b\x00\x00\x02\x01\"\x04\x00\x05'\x01\x00\x01^'\x01\x01\x00\x00\x00\x13*\n\x00^*\x01\x01\x00\x01+\x01\x03\x01,\b\x00\x00\x00\x00\x17\x00\x00\x00\x01\x00\x00\x00\"\x00\x00\x00\x04\x00\x00\x00,\x00\x00\x00\b\x00\x00\x00\x00"
```

**Comment by enebo** [comment]
You did not run my reproduction code as you changed the encoding:

```text
3.3.0 ~/work/gems/yarp main 1034% ruby -Ilib -rprism -e 'r = Prism.parse "# encoding: iso-8859-1\na = 'é'; puts a; a.encoding", encoding: "BINARY"; p r.source.source.encoding'
#<Encoding:ISO-8859-1>
3.3.0 ~/work/gems/yarp main 1035% ruby -Ilib -rprism -e 'r = Prism.parse "# encoding: utf-8\na = 'é'; puts a; a.encoding", encoding: "BINARY"; p r.source.source.encoding'
#<Encoding:ASCII-8BIT>
```

So seems to be something with UTF-8?  Not sure.

**Comment by eregon** [comment]
Ah right, sorry, I changed it to avoid any confusion with the default encoding but indeed it matters here.

**Comment by eregon** [comment]
More of a self-note, but this doesn't affect TruffleRuby because TruffleRuby already looks for the magic encoding comment before passing the source code to Prism, and so already knows it's UTF-8 and pass that as metadata, so the binary encoding is never seen by Prism for this case.
