### ISSUE TITLE
--enable-frozen-string-literal is overriding explicit pragmas when it shouldn't

### ISSUE THREAD

**Issue by enebo** [ruby/prism#2164]
This source encountered via mkmf when run with `ruby --enable-frozen-string-literal ../snippets/frozen2.rbl`:

```ruby
# -*- coding: us-ascii -*-
# frozen-string-literal: false

STRING_OR_FAILED_FORMAT = "%s"
def STRING_OR_FAILED_FORMAT.%(x) # :nodoc:
  x ? super : "failed"
end
```

Will error:

```text
FrozenError: can't modify frozen object: "%s"
```

The command-line flag is only intended to flag what to do when it is not explcitly specified by a top-line pragma.  It appears it is currently overriding it.

note: I am showing command-line here but I am really talking about specifying frozen in parse_and_serialize.

**Comment by kddnewton** [comment]
So you're saying you're passing `frozen` into `parse_and_serialize` but then it's _not_ being overridden by the magic comment?

**Comment by enebo** [comment]
@kddnewton I am but I should perhaps step through debugger and make sure.  The code looks like it is doing that.  I will double check.

**Comment by enebo** [comment]
@kddnewton yeah it is being set to 1 in what seems to be the right place (after encoding and before supress warnings).

**Comment by kddnewton** [comment]
Yup that makes sense!

**Comment by enebo** [comment]
@kddnewton I wonder if there are any other pragmas which can be false?  "warn_indent"?

**Comment by kddnewton** [comment]
Yeah for sure, but we don't support `warn_indent` at all atm... 😅
