### ISSUE TITLE
Java generated code should generate an enum (or static final ints) for versions once versioning is settled

### ISSUE THREAD

**Issue by enebo** [ruby/prism#2169]
I am manually writing 5 for 3.3 support in the request for serialized source but this ultimately should be passing a value that is referenced from code generated by prism.

There seems to still be some questions on how versioning will be handled and I will not need anything other than 3.3 support for at least a year so this is not all that important.  Just reminding us that we should add something eventually.

**Comment by eregon** [comment]
Indeed.
Currently the versions constants are only part of the header at https://github.com/ruby/prism/blob/5f46d364ae814edd21be9bb2f7b766b7d44123ca/include/prism/options.h#L32-L38

and in lib/prism/ffi.rb.

> I am manually writing 5

5 doesn't seem to correspond to any of these constants, but maybe I'm missing something?

The version for serialization seems not yet documented in https://github.com/ruby/prism/blob/main/docs/serialization.md but it was added in https://github.com/ruby/prism/pull/2118/files#diff-3eb9e99cab36d75a322185ffbcfb68f5337241fd0ad897c79359f87d5f2d510d, I'll make a PR for that.

It seems JRuby wants the same as TruffleRuby for now, nice (https://github.com/ruby/prism/issues/2163).

**Comment by enebo** [comment]
@eregon haha. I was not looking to closely I saw the 5 from the strncmp.  A case of moving too quickly to remove hs_err core dumps.

**Comment by kddnewton** [comment]
I think this is done now, unless I'm misreading.

**Comment by eregon** [comment]
Yes, added in https://github.com/ruby/prism/pull/2304
