### ISSUE TITLE
[CI] gcc-analyzer is not working

### ISSUE THREAD

**Issue by hasumikin** [ruby/prism#2181]
I found this issue in my PR #2171

## Summary of the issue

In https://github.com/ruby/prism/pull/1212/files#diff-7829468e86c1cc5d5133195b5cb48e1ff6c75e3e9203777f6b2e379d9e4882b3R195, the command `CFLAGS='-fanalyzer' bundle exec rake compile` seems to try to override CFLAGS defined in Makefile, but it doesn't work.
This is because variable definitions in the Makefile have priority over environment variables passed from the command line.

As a result, CI did not perform static analysis as intended.
Instead, passing the variable as an argument like `make CFLAGS=-fanalyzer` would work as you intend.

You can see what happens if you do `make clean && make CFLAGS=-fanalyzer` in your local machine.
It shows some warnings about non-null-expected, memory-leak, and double-freed.
The below log is a part of them (sorry, the text is a little garbled):

```
src/util/pm_newline_list.c: In function 窶湾m_newline_list_append窶・
src/util/pm_newline_list.c:33:9: warning: use of possibly-NULL 窶・list.offsets窶・where non-null expected [CWE-690] [-Wanalyzer-possible-null-argument]
   33 |         memcpy(list->offsets, original_offsets, list->size * sizeof(size_t));
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  窶湾m_newline_list_append窶・ events 1-4
    |
    |   28 |     if (list->size == list->capacity) {
    |      |        ^
    |      |        |
    |      |        (1) following 窶・rue窶・branch...
    |   29 |         size_t *original_offsets = list->offsets;
    |      |                 ~~~~~~~~~~~~~~~~
    |      |                 |
    |      |                 (2) ...to here
    |......
    |   32 |         list->offsets = (size_t *) calloc(list->capacity, sizeof(size_t));
    |      |                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    |      |                                    |
    |      |                                    (3) this call could return NULL
    |   33 |         memcpy(list->offsets, original_offsets, list->size * sizeof(size_t));
    |      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    |      |         |
    |      |         (4) argument 1 (窶・list.offsets窶・ from (3) could be NULL where non-null expected
    |
In file included from include/prism/defines.h:17,
                 from include/prism/util/pm_newline_list.h:17,
                 from src/util/pm_newline_list.c:1:
/usr/include/string.h:43:14: note: argument 1 of 窶藁emcpy窶・must be non-null
   43 | extern void *memcpy (void *__restrict __dest, const void *__restrict __src,
      |              ^~~~~~
```

## Possible solution

If you don't mind not treating warnings as errors, simply adding a new target to Makefile and a corresponding target to Rakefile would solve (note that the CFLAGS doesn't contain `-Werror` flag) like the following:

``` 
# Makefile
gcc-analyzer: CFLAGS := -fanalyzer -g -O2 -std=c99 -Wall -Wextra -Wpedantic -Wundef -Wconversion -Wno-missing-braces -fPIC -fvisibility=hidden
gcc-analyzer: all
```

```ruby
# Rakefile
task gcc_analyzer: [:templates] do
  sh "make gcc-analyzer"
end
```
 
```yaml
# .github/workflows/main.yml
  gcc-analyzer:
    (...)
    - name: Run build with gcc-analyzer enabled
      run: |
        bundle exec rake gcc_analyzer
```

Rather, if you want to strictly enforce the policy of treating warnings the same as errors, you will have to fix those warnings. (I tried to fix them. Although I could fix only a few of them, the rest of the warnings were difficult for me to solve. I gave up)

----

As in, I think `clang-analyzer` is not working, too.

https://github.com/ruby/prism/pull/1212/files#diff-7829468e86c1cc5d5133195b5cb48e1ff6c75e3e9203777f6b2e379d9e4882b3R210

I guess you should not have passed `bundle exec rake` as the subcommand of `scan-build`.
Instead, you will get some warnings if you directly pass `make` as the subcommand: just hit `scan-build make`.

Please check.

**Comment by kddnewton** [comment]
Ahh thank you for the report, this is definitely helpful. I'd like to get these fixed ASAP and then merge the changes you've suggested to ensure we don't regress.
