### ISSUE TITLE
[COMPILER] Remaining `defined?` cases

### ISSUE THREAD

**Issue by kddnewton** [ruby/prism#2188]
* [x] `BeginNode`
* [x] `BreakNode`
* [x] `CallAndWriteNode`
* [x] `CallOperatorWriteNode`
* [x] `CallOrWriteNode`
* [x] `CaseMatchNode`
* [x] `CaseNode`
* [x] `ClassNode`
* [x] `ConstantPathAndWriteNode`
* [x] `ConstantPathOperatorWriteNode`
* [x] `ConstantPathOrWriteNode`
* [x] `ConstantPathWriteNode`
* [x] `DefNode`
* [x] `DefinedNode`
* [x] `ForNode`
* [x] `IfNode`
* [x] `IndexAndWriteNode`
* [x] `IndexOperatorWriteNode`
* [x] `IndexOrWriteNode`
* [x] `InterpolatedSymbolNode`
* [x] `InterpolatedXStringNode`
* [x] `MatchRequiredNode`
* [x] `MatchWriteNode`
* [x] `ModuleNode`
* [x] `NextNode`
* [x] `RationalNode`
* [x] `RedoNode`
* [x] `RetryNode`
* [x] `ReturnNode`
* [x] `SingletonClassNode`
* [x] `UnlessNode`
* [x] `UntilNode`
* [x] `WhileNode`

At the moment all of these crash with `Unsupported node *`.

Not valid:

* [x] `PostExecutionNode`
* [x] `PreExecutionNode`
* [x] `RescueModifierNode`
* [x] `UndefNode`

**Comment by kddnewton** [comment]
@eileencodes would you be interested in working on this? No pressure either way, I just know you're familiar with this area of the code

**Comment by eileencodes** [comment]
I was just looking at this one and was going to ask to take it, so yes 😄

**Comment by eileencodes** [comment]
Batch 1 for this issue https://github.com/ruby/ruby/pull/9563

**Comment by eileencodes** [comment]
Batch 2 implements all the nodes that return `assignment` in the instructions https://github.com/ruby/ruby/pull/9579

**Comment by eileencodes** [comment]
The remaining nodes are implemented in https://github.com/ruby/ruby/pull/9588 and after that we can close this. Note that 4 nodes are not implemented, I cannot find a valid way to call `defined?` on `PostExecutionNode`, `PreExecutionNode`, `RescueModifierNode`, or `UndefNode`.
