### ISSUE TITLE
Prism::parse_file* APIs should raise appropriate errors

### ISSUE THREAD

**Issue by kddnewton** [ruby/prism#2207]
Right now, when you call any of these APIs:

* `Prism::dump_file`
* `Prism::lex_file`
* `Prism::parse_file`
* `Prism::parse_file_comments`
* `Prism::parse_lex_file`
* `Prism::parse_file_success?`

It will do a few things:

* Validate that the filepath is a string (or raise a `TypeError`)
* Try to open the file (or fail, call `perror` to print out the error for `errno`, and return `nil`)
* Try to stat the file (or fail, call `perror` to print out the error for `errno`, and return `nil`)
* Try to `mmap` the file (or fail, call `perror` and print out the error for `errno`, and return `nil`)
* Map the file, parse it, and return a parse result

I think we should change this behavior to raise an appropriate error. Fortunately, `errno` is set for us by `open`/`fstat`/`mmap`, so that is already in place. I think we should be able to call `rb_syserr_fail` with `errno` and the filepath and it should take care of everything for us. At that point `file_options` can return `void` because it will only ever exit through a Ruby error.

**Comment by eregon** [comment]
> * Validate that the filepath is a string (or raise a `TypeError`)

This seems to only happen for Prism.parse but not Prism.parse_file:
```
$ ruby -Ilib -rprism -e 'pp Prism.parse(nil)'
-e:1:in `parse': wrong argument type NilClass (expected String) (TypeError)

pp Prism.parse(nil)
               ^^^
	from -e:1:in `<main>'
zsh: exit 1     ruby -Ilib -rprism -e 'pp Prism.parse(nil)'

$ ruby -Ilib -rprism -e 'pp Prism.parse_file(nil)'
open: Bad address
nil
$ echo $?
0
```

**Comment by kddnewton** [comment]
Yes, `nil` is special-cased at the moment, that should be handled as well.

**Comment by duerst** [comment]
> Right now, when you call any of these APIs:
> 
> * `Prism::dump_file`
> * `Prism::lex_file`
> * `Prism::parse_file`
[snip]
> It will do a few things:
> 
> * Validate that the filepath is a string (or raise a `TypeError`)
[snip]

Shouldn't this be a bit more "duck-typed", so that e.g. a file can be passed directly or some other object can be the source of the code to be parsed?

**Comment by eregon** [comment]
These APIs are designed to be passed a filesystem path.
Passing a File object would be confusing because then it's not clear if it's going to use mmap or that File object to read the contents (mmap is much faster but e.g. wouldn't respect the offset in the File instance).

Maybe there could be `to_path` coercion, anyway this can always be added later.

**Comment by kddnewton** [comment]
> Shouldn't this be a bit more "duck-typed", so that e.g. a file can be passed directly or some other object can be the source of the code to be parsed?

I'm happy to add support for that, but that's not related to this ticket. We would need this kind of error generation regardless of whether or not we had called some kind of implicit coercion method or not.

**Comment by eileencodes** [comment]
CRuby compiler PR is here https://github.com/ruby/ruby/pull/9862
