### ISSUE TITLE
[COMPILER] Method calls in default values for keyword arguments returns nil

### ISSUE THREAD

**Issue by peterzhu2118** [ruby/prism#2248]
```ruby
def foo = 1
def assert_src_expected(args = nil, bar: foo) = bar
assert_src_expected
```

Should return `1` but instead returns `nil`.

**Comment by kddnewton** [comment]
It appears from this that optional keyword values are being evaluated before optional positional values, but it should be the opposite. We should wait until Aaron's PR lands which is changing some stuff, but this seems like a quick-ish fix.
