### ISSUE TITLE
Prism considers magic comments after the first non-comment line

### ISSUE THREAD

**Issue by eregon** [ruby/prism#2266]
```ruby
p 1
# coding: US-ASCII
p "a".encoding
```
Running it gives:
```
$ ruby test.rb
1
#<Encoding:UTF-8>
```
So the encoding comment is ignored, because magic encoding comments are IIRC only considered before any code/non-magic-comment token (except the shebang line).

```
$ bin/parse      
Comments:
...

Magic comments:
[#<Prism::MagicComment @key="coding" @value="US-ASCII">]

...
```
But Prism considers it as a magic comment.

**Comment by kddnewton** [comment]
Yes, this is by design. We don't know what consumers will want to do with magic comments, so we put all magic comments into the list. Not all magic comments have to be at the very top of the file.

**Comment by eregon** [comment]
> Not all magic comments have to be at the very top of the file.

AFAIK those are not magic comments, seeing how CRuby behaves.

Could you show me a case where the current behavior is necessary?
I cannot imagine one because this is incompatible with CRuby and so with Ruby semantics.

I think a magic comment is a comment with only other magic comments or the shebang line before it:
```ruby
# foo
# coding: US-ASCII
p "a".encoding
```
prints `#<Encoding:UTF-8>`

So I think it is a bug in Prism magic comment encoding, so I think this issue should be reopened and classified as such.

BTW, the magic *encoding* comment is a bit special in that it needs to be the first magic comment to have effect:
```ruby
# coding: US-ASCII
# frozen_string_literal: true
p "a".encoding # => US-ASCII
```
but
```ruby
# frozen_string_literal: true
# coding: US-ASCII
p "a".encoding # => UTF-8
```

**Comment by eregon** [comment]
This for instance causes an incompatibility for the `truffleruby_primitives` magic comment:
```ruby
p :hi
# truffleruby_primitives: true
p Primitive.undefined?(42)
```
```
$ ruby --experimental-options --prism=false test.rb
:hi
test.rb:3:in `const_missing': uninitialized constant Primitive (NameError)
	from test.rb:3:in `<main>'

$ ruby --experimental-options --prism=true test.rb 
:hi
false
```

And the same for `frozen_string_literal` although that might not be necessary to use given there are flags on StringNode, etc. Even if not used it sounds error-prone to list a `frozen_string_literal` as magic comment when CRuby doesn't consider it a magic comment.

**Comment by eregon** [comment]
I recalled that Ractor has some comments that can be not at the start of the file:
https://bugs.ruby-lang.org/issues/17273
```ruby
# shareable_constant_value: literal
A = "a"
p A.frozen? # => true
# shareable_constant_value: none
B = "b"
p B.frozen? # => false
```
These don't seem to be called magic comments but "pragmas" in that Redmine issue.

BTW `ruby --parser=prism ract.rb` shows 2 times `false` on 3.3.0. Possibly related to this issue?

If we want to treat these Ractor pragmas as magic comments then I think we'd need a boolean on Prism::MagicComment to know whether there are at the start of the file/source or not, to be compatible e.g. for `truffleruby_primitives` and other traditional file-level magic comments.

**Comment by eregon** [comment]
Mmh the logic in CRuby for this seems pretty indirect/not so readable.
* `encoding` can only be at the top: https://github.com/ruby/ruby/blob/a65b52b57f0b577a0486d5c05a1b5e6c53e6dc77/parse.y#L9654
* `frozen_string_literal` can only be before other tokens: https://github.com/ruby/ruby/blob/a65b52b57f0b577a0486d5c05a1b5e6c53e6dc77/parse.y#L9697
* https://github.com/ruby/ruby/blob/a65b52b57f0b577a0486d5c05a1b5e6c53e6dc77/parse.y#L10856-L10858 seems particularly confusing
* Other magic comments (barely ever used but they exist) seem to not require to be at the top of the file/before other tokens, which I guess is what you mean.

TruffleRuby only supports `encoding`, `frozen_string_literal` and `truffleruby_primitives` which all need to be at the top of the file, so I thought it's natural to only look at the start of the file for magic comments, and wasteful to look for them after. My mistake, that's not the logic in CRuby.

Therefore, could you reopen this to add a boolean on Prism::MagicComment to know whether a magic comment is at the start of the file/source or not? Or file a separate issue if you prefer.

**Comment by kddnewton** [comment]
Can you compare the start location of the program to the magic comment location? That appears to be what you want.

**Comment by eregon** [comment]
I would need to consider magic comments in lines before as well because e.g. in
```ruby
# encoding: US-ASCII
# frozen_string_literal: true
# truffleruby_primitives: true
code
```
All 3 comments are valid magic comments which have effect.

It's possible but it seems not so easy (e.g. the locations don't cover the whole line).

For now in TruffleRuby I think I will not use Prism's magic comments because they don't have easily the information I need / match what TruffleRuby considers as magic comments.
I anyway need to detect the magic encoding myself separately for the case of a Truffle Source provided as a java.lang.String (which I then need to convert to bytes using the magic encoding comment to pass to Prism).
I'll just extend that logic to also get the `truffleruby_primitives` magic comment.

If you have it at hand and it's already implemented, could you link to how magic comments are handled in CRuby with `--parser=prism`?
