### ISSUE TITLE
Interpolated strings new an empty string at the beginning

### ISSUE THREAD

**Issue by kddnewton** [ruby/prism#2271]
```ruby
a = 'Foo'
b = "#{a}" << 'Bar'
```

**Comment by enebo** [comment]
@kddnewton you mean you can visibly see old runtime effectively make an empty string so that the interpolated parts for `"#{a}"` is `["", emb_expr(a)]`?  This is old school mechanism (in AST at least) to have a string start with file encoding then get concat with whatever the string of the emb_expr creates?

JRuby solves this by implicitly creating that empty string first.  This may be what your bug is saying since it is marked compiler but I am just making sure.

**Comment by kddnewton** [comment]
Yeah this is just in the compiler, we won't be changing the AST to support this. If you look at the instructions for CRuby, you get:

```
== disasm: #<ISeq:<main>@test.rb:1 (1,0)-(2,19)> (catch: false)
local table (size: 2, argc: 0 [opts: 0, rest: -1, post: 0, block: -1, kw: -1@-1, kwrest: -1])
[ 2] a@0        [ 1] b@1
0000 putstring                              "Foo"                     (   1)[Li]
0002 setlocal_WC_0                          a@0
0004 putobject                              ""                        (   2)[Li]
0006 getlocal_WC_0                          a@0
0008 dup
0009 objtostring                            <calldata!mid:to_s, argc:0, FCALL|ARGS_SIMPLE>
0011 anytostring
0012 concatstrings                          2
0014 putstring                              "Bar"
0016 opt_ltlt                               <calldata!mid:<<, argc:1, ARGS_SIMPLE>[CcCr]
0018 dup
0019 setlocal_WC_0                          b@1
0021 leave
```

You can see `0004 putobject                              ""                        (   2)[Li]`. That's necessary for the encoding. We just haven't replicated that functionality in the compiler.

**Comment by enebo** [comment]
@kddnewton ok cool.  We do the same thing in IR that used to be given by AST (which I guess is still given in old parser but hey two empty strings are no big thing :smile: )

**Comment by kddnewton** [comment]
If you end up seeing issues here tagged with `compiler` it's almost entirely guaranteed that we're not going to be changing anything in the AST. We're just using it to track our work on CRuby without using ruby/ruby's issue tracker.

**Comment by enebo** [comment]
@kddnewton yeah I was fairly sure it was for the compiler and just making sure.  Some compiler tags actually effect how I do things in build so it is good to know.
