### ISSUE TITLE
Should we keep the verbose: keyword for Prism.parse?

### ISSUE THREAD

**Issue by eregon** [ruby/prism#2285]
From https://github.com/ruby/prism/pull/2265#issuecomment-1911079623

What do you want to do for the verbose option to `Prism.parse`? It's no longer necessary but maybe we should keep it for compatibility?
Same for the suppress warnings field in serialization.
Or maybe we should keep both as an optimization to avoid any overhead related to warnings?

I'd lean slightly toward removing them because one might expect `Prism.parse(verbose: v)` to be values of $VERBOSE but actually it's just a boolean for "include warnings (regardless of their verbosity) or exclude warnings in ParseResult".
So e.g. false/nil have the same effect while for $VERBOSE values they are different.

Currently `verbose: false` seems to have the effect to include no warnings in the ParseResult, so at least it does something:
```
$ PRISM_FFI_BACKEND=1 be ruby -Ilib -rprism -e 'pp Prism.parse("b +a")'
 @warnings=
  [#<Prism::ParseWarning @message="ambiguous first argument; put parentheses or a space even after `+` operator" @location=#<Prism::Location @start_offset=2 @length=1 start_line=1> @level=warning_verbose_true>]>

$ PRISM_FFI_BACKEND=1 be ruby -Ilib -rprism -e 'pp Prism.parse("b +a", verbose: false)'
 @warnings=[]>
```

**Comment by kddnewton** [comment]
I think we should remove it. It's behavior is a bit odd, and since we have the levels I don't think it's doing what you would think anymore.
