### ISSUE TITLE
[COMPILER] Multiple underscores in block parameter crashes

### ISSUE THREAD

**Issue by peterzhu2118** [ruby/prism#2295]
```ruby
[1].each { |(_, _, _, _, _, _)| }
```

**Comment by kddnewton** [comment]
I think this is solved by https://github.com/ruby/ruby/pull/9714

**Comment by kddnewton** [comment]
(Closing this)

**Comment by peterzhu2118** [comment]
I checked out https://github.com/ruby/ruby/pull/9714 and this does not appear to be fixed.

**Comment by kddnewton** [comment]
Ahh my bad! Can you open a PR against his branch?
