### ISSUE TITLE
Incompatibility with squiggly heredoc in `Prism::Translation::Parser`

### ISSUE THREAD

**Issue by koic** [ruby/prism#2374]
## Steps to reproduce the problem

This incompatibility occurs when using string interpolation within squiggly heredoc. It can be reproduced with Prism 0.21.0 and the following code:

```ruby
require 'prism'
require 'prism/translation/parser'
require 'parser/ruby33'

string_interpolation_in_squiggly_heredoc = <<~'RUBY'
  <<~HEREDOC
    #{x}
  HEREDOC
RUBY

p Prism::Translation::Parser.parse(string_interpolation_in_squiggly_heredoc).loc.heredoc_body.source
p Parser::Ruby33.parse(string_interpolation_in_squiggly_heredoc).loc.heredoc_body.source
```

Both expect leading whitespace to be present, but the result from `Prism::Translation::Parser` does not have any whitespace:

```console
$ ruby example.rb
"\#{x}\n"
"  \#{x}\n"
```

## Expected

It expects the presence of leading whitespace, similar to `Parser`, suggesting an expectation for compatibility.

## Actual

In `Prism::Translation::Parser`, there is no leading whitespace, indicating an incompatibility with `Parser::Ruby33`.

## Context

During the process of attempting Prism integration with RuboCop, this regression was discovered with `Layout/HeredocIndentation` cop.

**Comment by kddnewton** [comment]
Ahh I think I misunderstood. Parser doesn't strip common leading white space?

**Comment by kddnewton** [comment]
Oh I misunderstood, the locations are incorrect. I see.
