### ISSUE TITLE
[Feature][Ruby API] Implement `==` (value comparison) for `Prism::Node`

### ISSUE THREAD

**Issue by exterm** [ruby/prism#2465]
For testing, it would be great if we could compare ASTs.

It seems that value equality for nodes is just not defined. `Prism::Node#==` is inherited from BasicObject so it's only true if the two compared objects are the same object (object identity comparison). https://ruby-doc.org/3.2.2/BasicObject.html#method-i-3D-3D

It would be great to have value equality for nodes so we could do things like this:

```ruby
test "extract_argument_nodes extracts all argument nodes" do
  source = "class Entry; has_many :clowns, class_name: 'Order'; end"

  expected = Prism.parse(source).value.statements.body.first.body.body.first.arguments
  actual = extract_argument_nodes("class Entry; #{call}; end")
  
  assert_equal [expected], actual
end
```

Or even this: (ignoring node locations!)

```ruby
test "extract_argument_nodes extracts all argument nodes" do
  call = "has_many :clowns, class_name: 'Order'"

  expected = Prism.parse(call).body.first
  actual = extract_argument_nodes("class Entry; #{call}; end")
  
  assert_equal [expected], actual
end
```

From https://github.com/ruby/prism/discussions/2448

**Comment by eregon** [comment]
I'm unsure if it's right to have Node#== ignores location fields, because then it could consider "different nodes" to be ==, as in they are in different position in the source and also they might be completely unrelated logically (e.g. a RequiredParameterNode with a given name for one method vs for another method).
There is also the question of `eql?`, structural comparison ignoring locations there feels wrong.

You might have seen https://github.com/ruby/prism/blob/71991592d4cf97f64b311485f5985c766022d0f4/test/prism/test_helper.rb#L26
Maybe such a method should be exposed by the Prism gem?

**Comment by kddnewton** [comment]
I'm okay having a method for this, but not `#==`. Having that ignore location entirely would worry me for what consumers would accidentally find to be equal. I _would_ support this being `#===`, as that's closer semantics to "match"/"similar", which is what this request seems like it's asking for. That has the nice benefit of allowing you to use it in case expressions, as in your example:

```ruby
source = "class Entry; has_many :clowns, class_name: 'Order'; end"

case extract_argument_nodes("class Entry; #{call}; end")
when Prism.parse(source).value.statements.body.first.body.body.first.arguments
  # matched
end
```

**Comment by exterm** [comment]
Yeah, I agree it would be surprising if `#==` ignored location. It would still be nice to have a `#==` that takes the location into account (would enable my first example), and another method that doesn't take location into account (maybe `#===` as you propose).

Or just one of those. All of these options are improvements.

> Maybe such a method should be exposed by the Prism gem?

If the prism gem exposed `assert_equal_nodes`, that would solve my problem. However, I think it's a cleaner solution to implement `#==` and/or `#===` as they can be used independently of the environment you're in (not just minitest).

If I were to try implementing one or both of these, where would I start? Would you want this implemented in pure Ruby (which AFAICT would involve reopening a native class in Ruby)? Any pointers? 😃

**Comment by kddnewton** [comment]
All of the node classes are implemented in plain Ruby, no native classes. I think I would template out the method and make sure it compared against each of the fields. You would do this in `templates/lib/prism/node.rb.erb`.

**Comment by exterm** [comment]
Ah gosh it's an erb file, that's why I didn't find it
