### ISSUE TITLE
[BUG] Local with constant_id 171 does not exist

### ISSUE THREAD

**Issue by mrkn** [ruby/prism#2471]
In the pull-request https://github.com/ruby/ruby/pull/9581, test-all hangs up with the message `[BUG] Local with constant_id 171 does not exist`.
Could you please tell me how to resolve this problem?

**Comment by mrkn** [comment]
Sorry, this duplicates #2468 !!

**Comment by kddnewton** [comment]
Thanks @mrkn! I'll get this fixed quickly
