### ISSUE TITLE
Not properly parsing constant names

### ISSUE THREAD

**Issue by enebo** [ruby/prism#2477]
```ruby
class ᾈ
end
```
This is derived from test_parse.rb in MRI test suite which includes various other mbc values which are considered valid capital letters.  This also affects any use which needs to know it is a constant (e.g. defined?) but the parser throws a SyntaxError so we don't really make it to the point of executing this code.

**Comment by kddnewton** [comment]
I'm trying to figure out what's going on here. `"ᾈ".match?(/[[:upper:]]/)` is false, but so is `:lower:`, and `:alpha:` is true.

**Comment by enebo** [comment]
@kddnewton I am not saying it is related but I hang in MRI test_regexp.rb#test_char_class.  That tests a lot of stuff but if it is related you might have another path to seeing an issue.

**Comment by kddnewton** [comment]
I think I need to rederive the lookup tables. I'll do that tomorrow and I'm assuming that will fix this.
