### ISSUE TITLE
Prism::Translation::Parser multiline literals

### ISSUE THREAD

**Issue by kddnewton** [ruby/prism#2480]
Looks like the parser gem splits up multiline literals on newlines. I'm not sure it's actually an issue, but if we want to be 100% compatible, we will need to handle this.

```ruby
"foo
bar"

%x{
  date
}
```

**Comment by noahgibbs** [comment]
For full tilde-heredoc support we're probably doing the work for that internally regardless. With the differences between what they produce and what we do (e.g. for source location) I suspect we'll have to break it up into lines in any case.
