### ISSUE TITLE
Generated Javadoc comments (in Loader.java) fail to pass doclint

### ISSUE THREAD

**Issue by enebo** [ruby/prism#2488]
This is relatively unimportant near term but comments like:

```text
    /**
     * Represents a singleton class declaration involving the `class` keyword.
     *
     *     class << self end
     *     ^^^^^^^^^^^^^^^^^
     */
```

will cause javadoc processing to bail because `<` needs to be `&lt;`.  I think there are a few other cases like this.  Making an issue to not forget about it.

This was found because mvn release plugin crashes with a mysterious "exit code '1'" error and will not work by default.

**Comment by kddnewton** [comment]
Is it always HTML escaping?

**Comment by enebo** [comment]
@kddnewton yeah
