### ISSUE TITLE
Hash duplicated key check can be slow for huge code

### ISSUE THREAD

**Issue by tompng** [ruby/prism#2495]
If a huge hash keys are in ascending order, it is not slow
```ruby
irb(main):001> measure
TIME is added.
=> nil
irb(main):002> code = 1000000.times.to_h{[_1,1]}.inspect;
processing time: 0.317459s
irb(main):003> eval code;
processing time: 0.351567s
irb(main):004> Prism.parse_success? code
processing time: 0.308601s
=> true
```
Reversing the hash keys, it becomes about x200 slow
```ruby
irb(main):001> measure
TIME is added.
=> nil
irb(main):002> code = 1000000.times.reverse_each.to_h{[_1,1]}.inspect;
processing time: 0.353660s
irb(main):003> eval code;
processing time: 0.358981s
irb(main):004> Prism.parse_success? code
processing time: 75.626400s
=> true

```

**Comment by kddnewton** [comment]
Are you on the latest commit? We switched it to a binary search which should make it better. Maybe we need a hash lookup at this point though.

**Comment by tompng** [comment]
Yes, I'm on the latest commit. The binary search commit seems improved the ascending key case.
Perhaps finding insertion position by binary search is fast but memmove is not so fast for huge list.

**Comment by eregon** [comment]
To make it easier to follow, this is the code: https://github.com/ruby/prism/pull/2489/commits/a060b21e1d4b8d5a048eb8ec536cf5c97cc01486
Right, I think memmove() in the descending case is O(n^2).

**Comment by kddnewton** [comment]
Okay, I'll switch it to a hash map next week.
