### ISSUE TITLE
Can not install prism on RHEL 7

### ISSUE THREAD

**Issue by jcouball** [ruby/prism#2536]
Installing any recent versions of the prism gem on RHEL 7 is failing for me. Any advice would be appreciated.

Here is my configuration:

```
[user@server5 ~]$ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.9 (Maipo)
[user@server5 ~]$ gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[user@server5 ~]$ make --version
GNU Make 3.82
Built for x86_64-redhat-linux-gnu
Copyright (C) 2010  Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
[user@server5 ~]$ 
```

The errors I see are all like this:

```
src/prism.c: In function ‘parse_expression_prefix’:
src/prism.c:14677:17: error: missing initializer for field ‘arguments’ of ‘pm_arguments_t’ [-Werror=missing-field-initializers]
                 pm_arguments_t arguments = { 0 };
                 ^
src/prism.c:831:26: note: ‘arguments’ declared here
     pm_arguments_node_t *arguments;
                          ^
src/prism.c:14769:17: error: missing initializer for field ‘arguments’ of ‘pm_arguments_t’ [-Werror=missing-field-initializers]
                 pm_arguments_t arguments = { 0 };
                 ^
src/prism.c:831:26: note: ‘arguments’ declared here
     pm_arguments_node_t *arguments;
                          ^
```

I am not sure if I should turn off that error ... and I am not sure how to turn it off.

**Comment by kddnewton** [comment]
Hey there. It looks like you're hitting a bug from GCC 4 from back in 1998 (https://gcc.gnu.org/legacy-ml/gcc-bugs/1998-07/msg00031.html). You should be able to compile with `-Wno-missing-field-initializers` to turn it off. That being said, GCC-4 is not a compiler that Ruby supports, so you should upgrade to at minimum GCC-5 where it looks like this was fixed (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=61489).

**Comment by jcouball** [comment]
Thanks Kevin. I'll look into installing a more recent gcc or migrate to a newer OS version.

**Comment by jcouball** [comment]
Well, what do you know, with a compiler form the 2000s it worked! I am using gcc 5.3.1 and it worked. Will still look into getting even more modern, but at least I can move forward now.

Thanks for pointing me in the right direction, @kddnewton
