### ISSUE TITLE
Parse error on pattern expression with a quoted symbol in it

### ISSUE THREAD

**Issue by netrusov** [ruby/prism#2634]
### System configuration
I've tried different combinations of ruby/prism versions, picked the most recent for an example

```
$ ruby --version
ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [x86_64-linux]

$ ruby -r prism -e 'p Prism::VERSION'
"0.24.0"
```

### Steps to reproduce

here's a simplified example
```ruby
code = <<~RUBY
response = { status: 'ok', '3ds_status': 'redirect', url: 'url' }

case response
in { status: 'ok', '3ds_status': 'redirect', url: url }
  redirect_to url
in { status: 'ok' }
  status :ok
end
RUBY
```

### Current behavior

`prism` is unable to parse quoted symbol in pattern matching expression
```ruby
require 'prism'
Prism.parse(code).errors
# => [#<Prism::ParseError @message="expected a label after the `,` in the hash pattern" @location=#<Prism::Location @start_offset=99 @length=0 start_line=4> @level=:fatal>]
```

### Expected behavior

`prism` has to parse this expression correctly, the same code works with current parser with no problems
```ruby
require 'parser/current'
Parser::CurrentRuby.parse(code) # no errors
```

**Comment by netrusov** [comment]
I just accidentally found a workaround. If a quoted symbol is placed first, everything seems to work just fine

Change this:
```ruby
in { status: 'ok', '3ds_status': 'redirect', url: url }
```

To this:
```ruby
in { '3ds_status': 'redirect', status: 'ok', url: url }
```

It won't work with two such symbols though:
```ruby
in { '3ds_status': 'redirect', '4ds_status': 'collect', status: 'ok', url: url }
```

**Comment by kddnewton** [comment]
I plan to get to this this week btw. Out of curiosity, why are you using quotes at all?

**Comment by kddnewton** [comment]
Oh I see it has numbers.
