### ISSUE TITLE
Question: How can I create a new Prism node and pass in `source`?

### ISSUE THREAD

**Issue by seven1m** [ruby/prism#2772]
Since de203dca83a939effa9cca8a8be33c0c94a5f418 every new node requires a `source` be passed into the constructor. With Natalie, there are a few places where we synthesize a Prism node, such as [here](https://github.com/natalie-lang/natalie/blob/master/lib/natalie/parser.rb#L50-L52), utilized [here](https://github.com/natalie-lang/natalie/blob/master/lib/natalie/compiler/pass1.rb#L114), in order to make compilation a bit easier.

Is there a good way for me to keep doing that? I suspect that I would need the `source` object from the nearest node, or a parent node, but given that the `source` attr is private, I'm led to believe there might be a better way...

**Comment by kddnewton** [comment]
To be clear, all of the `source` objects that come from the same `ParseResult` object are actually the same object, we just keep a reference from every node/location because it makes it easier on the consumer. (Or in this case, much harder...)

**Comment by seven1m** [comment]
Oh, that's fine! I should have dug deeper... but it makes sense it would be the same object. Thanks!
