### ISSUE TITLE
Newline Token Handling in Multi-line Literals with `Prism.lex`

### ISSUE THREAD

**Issue by koic** [ruby/prism#2967]
I have a question about using `Prism.lex`, so I'm opening this issue.

## Expected

The expected token sequence from `Prism.lex` for a multi-line array literal without a trailing comma is as follows:

```console
$ cat example.rb
[
  foo,
  bar,
  baz
]
```

The token following the last element should perhaps be the `:IGNORED_NEWLINE` token, as shown below:

```console
$ ruby -rprism -e 'p Prism.lex(File.read("example.rb")).value.map(&:first).map(&:type)'
[:BRACKET_LEFT_ARRAY, :IGNORED_NEWLINE, :IDENTIFIER, :COMMA, :IGNORED_NEWLINE, :IDENTIFIER, :COMMA, :IGNORED_NEWLINE, :IDENTIFIER, :IGNORED_NEWLINE, :BRACKET_RIGHT, :NEWLINE, :EOF]
```

## Actual

The token following the last element is the `:NEWLINE` token, as shown below:

```console
$ ruby -rprism -e 'p Prism.lex(File.read("example.rb")).value.map(&:first).map(&:type)'
[:BRACKET_LEFT_ARRAY, :IGNORED_NEWLINE, :IDENTIFIER, :COMMA, :IGNORED_NEWLINE, :IDENTIFIER, :COMMA, :IGNORED_NEWLINE, :IDENTIFIER, :NEWLINE, :BRACKET_RIGHT, :NEWLINE, :EOF]
```

## Supplementary Information

The token sequence from `Prism.lex` for a multi-line array literal with a trailing comma is as follows:

```console
$ cat example.rb
[
  foo,
  bar,
  baz,
]
```

The token following the trailing comma of the last element is the `:IGNORED_NEWLINE` token, as shown below:

```console
$ ruby -rprism -e 'p Prism.lex(File.read("example.rb")).value.map(&:first).map(&:type)'
[:BRACKET_LEFT_ARRAY, :IGNORED_NEWLINE, :IDENTIFIER, :COMMA, :IGNORED_NEWLINE, :IDENTIFIER, :COMMA, :IGNORED_NEWLINE, :IDENTIFIER, :COMMA, :IGNORED_NEWLINE, :BRACKET_RIGHT, :NEWLINE, :EOF]
```

I think that the newline before the `:BRACKET_RIGHT` token should always be `:IGNORED_NEWLINE` token regardless of whether the trailing comma is present or not, as they have the same semantics.

NOTE: This also applies to cases using `:PARENTHESIS_RIGHT` token and `:BRACE_RIGHT` token.

I'm not sure if this is expected behavior or should be considered a bug, but I'm providing this feedback as an issue.

**Comment by kddnewton** [comment]
I agree with you this is odd behavior, but for the lexer specifically I've been trying to match the existing parser for compatibility reasons. So until we are merged as the default, I'm reluctant to change it. For example:

```
irb(main):001> Ripper.lex("[\nfoo\n]\n")
=> 
[[[1, 0], :on_lbracket, "[", BEG|LABEL],
 [[1, 1], :on_ignored_nl, "\n", BEG|LABEL],
 [[2, 0], :on_ident, "foo", ARG],
 [[2, 3], :on_nl, "\n", BEG],
 [[3, 0], :on_rbracket, "]", END],
 [[3, 1], :on_nl, "\n", BEG]]
```

So for now, I'd like to keep it as is. But if this is chosen as the default parser, it's definitely something I would like to change in the future.
