### ISSUE TITLE
Inconsistent return types for `Prism.lex` and `Prism.lex_file` depending on `prism/ffi` requirement

### ISSUE THREAD

**Issue by koic** [ruby/prism#2984]
This is a question from the user's perspective. The result class of `Prism.lex` differs depending on whether `require 'prism/ffi'` is used or not.

Without `prism/ffi`, `Prism::ParseLexResult` is returned:

```console
$ ruby -Ilib -rprism -e 'p Prism.lex("puts:hello").class'
Prism::ParseLexResult
```

With `prism/ffi`, `Prism::LexResult` is returned:

```console
$ ruby -Ilib -rprism -rprism/ffi -e 'p Prism.lex("puts:hello").class'
Prism::LexResult
```

The same result occurs with `Prism.lex_file`.

## Expected Behavior

I expected the return value of `Prism.lex` and `Prism.lex_file` to be consistent as either `Prism::ParseLexResult` or `Prism::LexResult`, regardless of whether `require 'prism/ffi'` is used.

## Actual Behavior

The result class differs depending on whether `require 'prism/ffi'` is used. It seems that the return value should be consistent as either `Prism::ParseLexResult` or `Prism::LexResult`, but I'm not sure which one it should be.

**Comment by kddnewton** [comment]
Yeah, this is a bug. `lex` and `lex_file` should both return `LexResult`. Thanks for the report I'll get it fixed.

**Comment by koic** [comment]
Thanks for the quick fix!
