### ISSUE TITLE
Missing `CONTAINS_SPLAT` counterpart for Hash nodes

### ISSUE THREAD

**Issue by amomchilov** [ruby/prism#3057]
Arrays have the `PM_ARRAY_NODE_FLAGS_CONTAINS_SPLAT` flag, which tells you if there's a `*splat`, or if all the elements are just plain elements.

https://github.com/ruby/prism/blob/acfeadec16ce001ab7e6a32701bb869f14abca84/config.yml#L661-L664

There's nothing equivalent to this for `PM_HASH_NODE` or `PM_KEYWORD_HASH_NODE` for knowing whether or not there's a `**splat`, so each element needs to always be type-checked for `PM_ASSOC_NODE` vs `PM_ASSOC_SPLAT_NODE`.

**Comment by kddnewton** [comment]
@amomchilov is this something you would need for Sorbet? I'm trying to figure out the use-case here. The flags in the array are because you might be able to get away with not duplicating an array if there's a splat, so it's mostly a compiler-level concern.

**Comment by kddnewton** [comment]
Feel free to comment back on here if this is something you need!

**Comment by amomchilov** [comment]
Ah I was away on vacation :)

I didn't know this was just to support the compiler. I don't really _need_ this, so don't worry about it.

Originally I wrote this because _if_ did it exist, I would have used it for a fast-path (to to treat all elements of a Hash as a `PM_ASSOC_NODE` without explicitly checking each one's type ID). Real world hash literals are relatively small, and this check is so fast anyway, that it probably wouldn't have helped much.
