### ISSUE TITLE
Nested alternanation pattern matching bug in 3.4.0-rc1

### ISSUE THREAD

**Issue by nevans** [ruby/prism#3312]
My apologies if this has already been fixed in `prism`.  I didn't see anything about it in a quick skimming of the commit log and issues.  My apologies also that I haven't made a `prism` specific test case.  I created a ruby issue for it first, and only realized that prism is somehow involved afterwards: https://bugs.ruby-lang.org/issues/20956.  I'll copy the text from that ticket here:

I think I've found a pattern matching bug in ruby 3.4.0-rc1.

```ruby
[123, ["foo"]] in [_, /\Afoo\b/i | [/\Afoo\z/i, *]]
```
I also tested this in ruby 2.7.8, with:
```ruby
case [123, ["foo"]]; in [_, /\Afoo\b/i | [/\Afoo\z/i, *]] then true; else false end
```

These return `true` in ruby 2.7.8, 3.0.7, 3.1.6, 3.2.6, and 3.3.6.
But they return false in 3.4.0-rc1.

I'm not sure if this is the best example, but it is a simplification of how I came across the bug.

Here are some other similar cases, which give the same result in 3.4.0-rc1 and 3.3.6:
```ruby
irb(main):001> ["foo"] in /\Afoo\b/i | [/\Afoo\z/i, *]
=> true
irb(main):002> [123, ["foo"]] in [_, [/\Afoo\z/i, *]]
=> true
irb(main):003> [["foo"]] in [[/\Afoo\z/i, *]]
=> true
```

But this case exhibits the bug again:
```ruby
irb(main):004> [["foo"]] in [/\Afoo\b/i | [/\Afoo\z/i, *]]
=> false
```

After further debugging, this would appear to be a bug in prism, or prism-adjacent code?

```console
$ ruby -e 'pp ([["foo"]] in [/\Afoo\b/i | [/\Afoo\z/i, *]])'
false

$ ruby --parser=parse.y -e 'pp ([["foo"]] in [/\Afoo\b/i | [/\Afoo\z/i, *]])'
true
```

**Comment by kddnewton** [comment]
Thanks I'll check it out!

**Comment by kddnewton** [comment]
This should be all fixed up on `master` now.
