### ISSUE TITLE
Compatibility issue between parse.y and Prism on the string returned by Hash#inspect

### ISSUE THREAD

**Issue by lidimayra** [ruby/prism#3357]
I noted different results from `Hash#inspect` when switching to Ruby 3.4 (example [here](https://github.com/jnunemaker/httparty/issues/807)).

## Ruby 3.3
```ruby
> {foo: "bar"}.inspect
=> "{:foo=>\"bar\"}"
```

## Ruby 3.4
```ruby
> {foo: "bar"}.inspect
=> "{foo: \"bar\"}"
```

**Comment by kddnewton** [comment]
That has nothing to do with Prism, it's an intentional change by the core team. Please see the Ruby 3.4 release notes https://www.ruby-lang.org/en/news/2024/12/25/ruby-3-4-0-released/.
