### ISSUE TITLE
Parse other magic comments besides encoding

### ISSUE THREAD

**Issue by kddnewton** [ruby/prism#574]
To support compilation, we will need to store various other options enabled by magic comments. Particularly the `frozen_string_literal` pragma. We will need to both parse this and store it on the parser.

**Comment by eregon** [comment]
We need this in the serialized output as well of course. IMO it should accept arbitrary keys and values, and can be stored like a list/array of strings in the serialized form

**Comment by eregon** [comment]
One thought about when looking with @andrykonchin today is for serialization we could serialize this next to the encoding, as `varint number of magic comments; [magic comment name, magic comment value]*`.
We'd need `yp_parse()` to store the magic encodings somewhere though (unless it does already?)
