### ISSUE TITLE
Double parsing arguments

### ISSUE THREAD

**Issue by haldun** [ruby/prism#739]
In codes like

```ruby
foo() 4
```

we call `parse_arguments_list` twice for the identifier `foo`. The first one happens in `parse_identifier` and when it returns a call node, then we check the arguments again here 
https://github.com/Shopify/yarp/blob/03d704fa6f3b39df780a3d4db1629610a5789065/src/yarp.c#L9075-L9095

**Comment by kddnewton** [comment]
Yikes! That's a bug for sure. Thanks for finding this.
