### ISSUE TITLE
Fix heredocs with leading spaces

### ISSUE THREAD

**Issue by jemmaissroff** [ruby/prism#753]
```
puts <<-'    ABC'
marker with spaces
    ABC
```

```
puts <<~'    ABC'
marker with spaces
    ABC
```

Worth noting that this behavior recently changed upstream:
* [bug report](https://bugs.ruby-lang.org/issues/19539)
* [fix](https://github.com/ruby/ruby/commit/67dd52d59cde0d2f1ebb3e299b605ed239b59f5b)

**Comment by kddnewton** [comment]
@haldun do you think you could take a look at this one?

**Comment by kddnewton** [comment]
@haldun if it's alright, I'm going to assign this one to you. I know we talked about pairing on it, which we can do next week.

**Comment by kddnewton** [comment]
Ahh nvm... I guess I can't assign it to you?

**Comment by kddnewton** [comment]
@haldun  I just invited to the repository, let me know when you accept and then I'll assign this one to you.

**Comment by haldun** [comment]
Accepted.

**Comment by kddnewton** [comment]
Nice
