### ISSUE TITLE
Huge performance issue in character processing (tl;dr UTF-8 encoding methods are too slow for full time use)

### ISSUE THREAD

**Issue by enebo** [ruby/prism#772]
I was examining speed and loading a file thousands of times.  This was loading and executing in JRuby.  Once I realized it was not compiled with optimizations enabled (used -O3)  I still noticed it was 2+x slower than JRuby's parser.  22s vs 9.8s.  I ran with async profiler and 75% of the profile was spent in 2 methods yp_encoding_utf8_alnum and yp_encoding_utf_8_isupper_char.  I then changed the file being parsed to use ```encoding: ascii``` and then Yarp on JRuby was 5.5s vs 9.8s.  Most files are generally 7 bit ASCII even though the default is UTF-8.

C Ruby's parser goes through lengths to try and stay in 7bit ASCII parsing land.  For identifiers/keywords, it has a cheap ```ISASCII()``` check and if it fails then it bails to a precise codepoint route.  This almost never happens so unsurprisingly it is a big win.  Most text even in a file containing mbc is mostly 7 bit ASCII.

For strings and heredocs it also hopes for ascii when encoding itself supports ASCII and fails to slower encoding methods when they notice.

The other thing to point out is when they do this they also track code range (unknown, 7bit, valid, broken) and it gets used for Strings to optimize better during execution.  So I think YARP will need to add this and definitely change how encoding it done.

**Comment by HParker** [comment]
I also saw `yp_encoding_utf8_alnum` in my profiling as well,

<img width="1789" alt="Screenshot 2023-04-05 at 11 00 34 PM" src="https://user-images.githubusercontent.com/4482399/230284993-46357062-d371-49f7-84d7-c8916c21fc90.png">


I don't see `yp_encoding_utf_8_isupper_char`, but I think I need to do like you did and process a file thousands of times. Right now `YARP.parse` is dominated by node creation time.

Good news is the call path looks really linear, so it might not be that hard to do like you suggest and add a fast `ISASCII()` check.

**Comment by HParker** [comment]
Put together something we can profile together: https://github.com/Shopify/yarp/pull/773

I'll run it through some profiling tomorrow.

**Comment by flavorjones** [comment]
Slightly tangential: there is prior art to performant decoding in C that may be worth looking at to speed up the unicode decoding as well. The gumbo parser (invented at Google and now maintained in the Nokogiri code base) uses the code described here: https://bjoern.hoehrmann.de/utf-8/decoder/dfa/

The implementation in gumbo can probably be dropped into YARP if you want to try profiling it along with the other approaches you're considering:

https://github.com/sparklemotion/nokogiri/blob/main/gumbo-parser/src/utf8.c#L40-L88

**Comment by HParker** [comment]
@enebo Do you have a benchmark I can run with just YARP that reproduces the,

> 75% of the profile was spent in 2 methods yp_encoding_utf8_alnum and yp_encoding_utf_8_isupper_char

finding?

I am having a hard time getting YARP to spend that much time in those methods.

**Comment by enebo** [comment]
@HParker That was within JRuby being consumed via JNI serialized data and it stood out like that.  I could not see this at all until I optimized (-O3) the files.  Are you using an optimized build?

**Comment by HParker** [comment]
I turned on -O3 and tried with the `BUNDLE` build and I can't get it over 3% time spent in alnum. Let me try profiling the serializer next Maybe there is something else in serialize that is causing this increase.

**Comment by enebo** [comment]
@HParker I have numbers using your PR benchmark on the PR itself

**Comment by eregon** [comment]
I guess we can close this now?
