### ISSUE TITLE
Eval parsing needs to pass in surrounding variable scopes.

### ISSUE THREAD

**Issue by enebo** [ruby/prism#821]
YARP has no concept of eval parsing.  Consider:

```ruby
b = 1

proc {
  c = 2

  eval "b = c"

  p b
}.call

p b
```

Eval needs the concept of external variable definitions.  Calling eval should reference the ```b``` outside the proc and the ```c``` in the proc.  Without a way of passing this into into YARP it will make a new depth 0 variable in the eval scope for ```b``` and ```c``` will become a CallNode.

**Comment by eregon** [comment]
Ah yes, YARP needs the depth, because `LocalVariableReadNode` stores the depth (as `type: integer`).

**Comment by enebo** [comment]
I looked at this for a short bit this afternoon.  ```yp_parse_serialize``` either can get another parameter for scopes OR there can be a second method just for parsing evals.  In either case how that parameter is passed I think will be challenging.  The current definition of yp_token_t is marked by a type and a start/end offset where the identifier is in source.  For eval's the surrounding parent scope source is very likely long gone.  So start/end will have to point at something?

Logically we need to pass in a list of viewable lexical scopes.  For the following code:

```ruby
a = 1
proc {
  b = 2
  eval "puts a, b"
}.call
```

We would need to pass something resembling an like (I don't think type of scope is important for these so long as the requirement is we only pass in visible scopes):

```text
[:b, parent -> [:a, parent -> null]]
```

For serialization purposes we will not be using C structs so this needs to be encoded.  The simplest would be single array:

```text
[2, 1, "a", 1, "b"]
```

Where 2 is number of scopes
 
both 1's are how many identifiers are per scope

Can this be a ```char *``` so that ```yp_token_t``` can just index into this array?  How do we deal with multiple encodings?

**Comment by enebo** [comment]
I have a start on a WIP for this.  The main problem with it is that it only uses a single byte for number of scopes and number of variables in a scope.  I do not think is a reasonable upper bound but should I use 4 bytes per value?  The amount of encoded data is very small so I do not think that is a concern.  Just feels weird to think we have 32 bits worth of scopes or lvars in a scope :smile:

**Comment by enebo** [comment]
WIP in #1171
